/* Language switch for the Baril Coatings product-line one-pagers.
   English is authored in the DOM; NL / PL / RO live in the maps below.
   <body data-brand="..."> picks the per-page map; COMMON applies to all.
   Shares the 'baril-coatings-lang' key with the rest of the Coatings site.
   PL/RO are machine translations — refine as needed. */
(() => {
  'use strict';

  const COMMON = [
    ['.navlinks a', {
      nl: ['Aquaran','DualCure','SteelKote','Bariline','Alle producten'],
      pl: ['Aquaran','DualCure','SteelKote','Bariline','Wszystkie produkty'],
      ro: ['Aquaran','DualCure','SteelKote','Bariline','Toate produsele'],
      de: ['Aquaran','DualCure','SteelKote','Bariline','Alle Produkte'],
      fr: ['Aquaran','DualCure','SteelKote','Bariline','Tous les produits'],
      es: ['Aquaran','DualCure','SteelKote','Bariline','Todos los productos'],
      it: ['Aquaran','DualCure','SteelKote','Bariline','Tutti i prodotti'],
      tr: ['Aquaran','DualCure','SteelKote','Bariline','Tüm ürünler'], no: ['Aquaran','DualCure','SteelKote','Bariline','Alle produkter'], sv: ['Aquaran','DualCure','SteelKote','Bariline','Alla produkter'] }],
    ['.bp-hero .btn-accent', { nl: 'Bekijk producten', pl: 'Zobacz produkty', ro: 'Vezi produsele', de: 'Produkte ansehen', fr: 'Voir les produits', es: 'Ver productos', it: 'Scopri i prodotti', tr: 'Ürünleri keşfedin', no: 'Se produkter', sv: 'Se produkter' }],
    ['.bp-hero .btn-ghost', { nl: 'Praat met een expert', pl: 'Porozmawiaj z ekspertem', ro: 'Discută cu un expert', de: 'Mit einem Experten sprechen', fr: 'Parler à un expert', es: 'Hablar con un experto', it: 'Parla con un esperto', tr: 'Bir uzmanla konuşun', no: 'Snakk med en ekspert', sv: 'Prata med en expert' }],
    ['.bp-band .btn-accent', { nl: 'Bekijk de catalogus', pl: 'Przeglądaj katalog', ro: 'Răsfoiește catalogul', de: 'Katalog durchstöbern', fr: 'Parcourir le catalogue', es: 'Explorar el catálogo', it: 'Sfoglia il catalogo', tr: 'Kataloğa göz atın', no: 'Bla i katalogen', sv: 'Bläddra i katalogen' }],
    ['.bp-band .btn-ghost', { nl: 'Praat met een expert', pl: 'Porozmawiaj z ekspertem', ro: 'Discută cu un expert', de: 'Mit einem Experten sprechen', fr: 'Parler à un expert', es: 'Hablar con un experto', it: 'Parla con un esperto', tr: 'Bir uzmanla konuşun', no: 'Snakk med en ekspert', sv: 'Prata med en expert' }],
    ['.foot-grid h3', { nl: ['Productlijnen','Baril Coatings'], pl: ['Linie produktów','Baril Coatings'], ro: ['Linii de produse','Baril Coatings'], de: ['Produktlinien','Baril Coatings'], fr: ['Gammes de produits','Baril Coatings'], es: ['Líneas de producto','Baril Coatings'], it: ['Linee di prodotto','Baril Coatings'], tr: ['Ürün hatları','Baril Coatings'], no: ['Produktlinjer','Baril Coatings'], sv: ['Produktlinjer','Baril Coatings'] }],
    ['.foot-grid div:nth-child(3) a', {
      nl: ['Home','Alle producten','Contact','Baril Group →'],
      pl: ['Strona główna','Wszystkie produkty','Kontakt','Baril Group →'],
      ro: ['Acasă','Toate produsele','Contact','Baril Group →'],
      de: ['Startseite','Alle Produkte','Kontakt','Baril Group →'],
      fr: ['Accueil','Tous les produits','Contact','Baril Group →'],
      es: ['Inicio','Todos los productos','Contacto','Baril Group →'],
      it: ['Home','Tutti i prodotti','Contatto','Baril Group →'],
      tr: ['Ana sayfa','Tüm ürünler','İletişim','Baril Group →'], no: ['Hjem','Alle produkter','Kontakt','Baril Group →'], sv: ['Hem','Alla produkter','Kontakt','Baril Group →'] }],
    ['.foot-bottom span', {
      nl: ["© Baril Coatings · 's-Hertogenbosch NL · onderdeel van Baril Group", 'Meer beschermen, met minder.'],
      pl: ["© Baril Coatings · 's-Hertogenbosch NL · część Baril Group", 'Chroń więcej, używając mniej.'],
      ro: ["© Baril Coatings · 's-Hertogenbosch NL · parte din Baril Group", 'Protejează mai mult, cu mai puțin.'],
      de: ['© Baril Coatings · \'s-Hertogenbosch NL · Teil der Baril Group', 'Mehr schützen, mit weniger.'],
      fr: ['© Baril Coatings · \'s-Hertogenbosch NL · membre de Baril Group', 'Protéger plus, avec moins.'],
      es: ['© Baril Coatings · \'s-Hertogenbosch NL · parte de Baril Group', 'Proteger más, con menos.'],
      it: ['© Baril Coatings · \'s-Hertogenbosch NL · parte di Baril Group', 'Proteggere di più, con meno.'],
      tr: ['© Baril Coatings · \'s-Hertogenbosch NL · Baril Group bünyesinde', 'Daha azıyla daha çok koruma.'], no: ['© Baril Coatings · \'s-Hertogenbosch NL · en del av Baril Group','Mer beskyttelse, med mindre.'], sv: ['© Baril Coatings · \'s-Hertogenbosch NL · en del av Baril Group','Mer skydd, med mindre.'] }]
  ];

  const MAPS = {
    aquaran: [
      ['.bp-tag', { nl: 'Watergedragen beschermende coatings', pl: 'Wodorozcieńczalne powłoki ochronne', ro: 'Acoperiri de protecție pe bază de apă', de: 'Wasserbasierte Schutzbeschichtungen', fr: 'Revêtements de protection à base d\'eau', es: 'Recubrimientos protectores al agua', it: 'Rivestimenti protettivi a base acqua', tr: 'Su bazlı koruyucu kaplamalar', no: 'Vannbaserte beskyttende belegg', sv: 'Vattenburna skyddande beläggningar' }],
      ['.bp-sub', {
        nl: 'Watergedragen 1K- &amp; 2K-beschermende coatings voor industriële afwerking en staal — <strong>de bescherming van solventsystemen, met veel minder emissies</strong>.',
        pl: 'Wodorozcieńczalne powłoki ochronne 1K i 2K do wykańczania przemysłowego i stali — <strong>ochrona systemów rozpuszczalnikowych, przy znacznie mniejszej emisji</strong>.',
        ro: 'Acoperiri de protecție 1K și 2K pe bază de apă pentru finisare industrială și oțel — <strong>protecția sistemelor cu solvenți, cu emisii mult mai reduse</strong>.',
        de: 'Wasserbasierte 1K- &amp; 2K-Schutzbeschichtungen für die Industrieveredelung und Stahl — <strong>der Schutz von Lösemittelsystemen, mit deutlich geringeren Emissionen</strong>.',
        fr: 'Revêtements de protection 1K &amp; 2K à base d\'eau pour la finition industrielle et l\'acier — <strong>la protection des systèmes solvantés, avec des émissions bien moindres</strong>.',
        es: 'Recubrimientos protectores 1K &amp; 2K al agua para acabado industrial y acero — <strong>la protección de los sistemas con disolvente, con muchas menos emisiones</strong>.',
        it: 'Rivestimenti protettivi 1K &amp; 2K a base acqua per la finitura industriale e l\'acciaio — <strong>la protezione dei sistemi a solvente, con emissioni nettamente inferiori</strong>.',
        tr: 'Endüstriyel son kat ve çelik için su bazlı 1K &amp; 2K koruyucu kaplamalar — <strong>solvent sistemlerinin koruması, çok daha az emisyonla</strong>.', no: 'Vannbaserte 1K- &amp; 2K-beskyttende belegg for industriell finish og stål — <strong>beskyttelsen fra løsemiddelsystemer, med langt færre utslipp</strong>.', sv: 'Vattenburna 1K- &amp; 2K-skyddande beläggningar för industriell finish och stål — <strong>skyddet från lösningsmedelssystem, med långt färre utsläpp</strong>.' }],
      ['.bp-quick span', {
        nl: ['<b>1K &amp; 2K</b> systemen','<b>C1–C5</b> corrosiviteit','<b>Low-VOC</b> watergedragen','Staal · aluminium · verzinkt'],
        pl: ['Systemy <b>1K i 2K</b>','Korozyjność <b>C1–C5</b>','<b>Low-VOC</b> wodorozcieńczalne','Stal · aluminium · ocynk'],
        ro: ['Sisteme <b>1K &amp; 2K</b>','Corozivitate <b>C1–C5</b>','<b>Low-VOC</b> pe bază de apă','Oțel · aluminiu · zincat'],
        de: ['<b>1K &amp; 2K</b> Systeme','<b>C1–C5</b> Korrosivität','<b>Low-VOC</b> wasserbasiert','Stahl · Aluminium · verzinkt'],
        fr: ['Systèmes <b>1K &amp; 2K</b>','Corrosivité <b>C1–C5</b>','<b>Low-VOC</b> à base d\'eau','Acier · aluminium · galvanisé'],
        es: ['Sistemas <b>1K &amp; 2K</b>','Corrosividad <b>C1–C5</b>','<b>Low-VOC</b> al agua','Acero · aluminio · galvanizado'],
        it: ['Sistemi <b>1K &amp; 2K</b>','Corrosività <b>C1–C5</b>','<b>Low-VOC</b> a base acqua','Acciaio · alluminio · zincato'],
        tr: ['<b>1K &amp; 2K</b> sistemler','<b>C1–C5</b> korozyon','<b>Low-VOC</b> su bazlı','Çelik · alüminyum · galvaniz'], no: ['<b>1K &amp; 2K</b>-systemer','<b>C1–C5</b> korrosivitet','<b>Lav-VOC</b> vannbasert','Stål · aluminium · galvanisert'], sv: ['<b>1K &amp; 2K</b>-system','<b>C1–C5</b> korrosivitet','<b>Låg-VOC</b> vattenburen','Stål · aluminium · galvaniserat'] }],
      ['.eyebrow', { nl: ['Waarom Aquaran','In de praktijk'], pl: ['Dlaczego Aquaran','W praktyce'], ro: ['De ce Aquaran','În practică'], de: ['Warum Aquaran','In der Praxis'], fr: ['Pourquoi Aquaran','En pratique'], es: ['Por qué Aquaran','En la práctica'], it: ['Perché Aquaran','Nella pratica'], tr: ['Neden Aquaran','Pratikte'], no: ['Hvorfor Aquaran','I praksis'], sv: ['Varför Aquaran','I praktiken'] }],
      ['.bp-quote', {
        nl: 'Bescherming hoeft de lucht eromheen niet te kosten. Aquaran levert duurzame, industriële coatingprestaties op waterbasis — <em>vergelijkbaar met solventsystemen</em>, met een fractie van de VOS.',
        pl: 'Ochrona nie musi kosztować otaczającego powietrza. Aquaran zapewnia trwałe, przemysłowe właściwości powłoki na bazie wody — <em>porównywalne z systemami rozpuszczalnikowymi</em>, przy ułamku LZO.',
        ro: 'Protecția nu trebuie să coste aerul din jur. Aquaran oferă performanțe de acoperire durabile, de nivel industrial, pe bază de apă — <em>comparabile cu sistemele cu solvenți</em>, cu o fracțiune din COV.',
        de: 'Schutz muss nicht die Luft ringsum kosten. Aquaran liefert dauerhafte, industrielle Beschichtungsleistung auf Wasserbasis — <em>vergleichbar mit Lösemittelsystemen</em>, mit einem Bruchteil der VOC.',
        fr: 'La protection ne doit pas se payer au prix de l\'air alentour. Aquaran offre des performances de revêtement industrielles et durables à base d\'eau — <em>comparables aux systèmes solvantés</em>, avec une fraction des COV.',
        es: 'La protección no tiene por qué costar el aire que la rodea. Aquaran ofrece un rendimiento de recubrimiento industrial y duradero al agua — <em>comparable a los sistemas con disolvente</em>, con una fracción de los COV.',
        it: 'La protezione non deve costare l\'aria che la circonda. Aquaran offre prestazioni di rivestimento industriali e durature a base acqua — <em>paragonabili ai sistemi a solvente</em>, con una frazione dei COV.',
        tr: 'Koruma, çevredeki havaya mal olmak zorunda değildir. Aquaran, su bazlı dayanıklı ve endüstriyel kaplama performansı sunar — <em>solvent sistemleriyle kıyaslanabilir</em>, VOC\'nin küçük bir kısmıyla.', no: 'Beskyttelse trenger ikke gå på bekostning av lufta rundt. Aquaran gir slitesterk, industriell beleggsytelse på vannbasis — <em>sammenlignbar med løsemiddelsystemer</em>, med en brøkdel av VOC-en.', sv: 'Skydd behöver inte kosta luften omkring. Aquaran ger slitstark, industriell beläggningsprestanda på vattenbas — <em>jämförbar med lösningsmedelssystem</em>, med en bråkdel av VOC:n.' }],
      ['.bp-card b', {
        nl: ['Lage VOS-emissies','1K- &amp; 2K-opties','Multi-ondergrond','C1–C5 corrosiviteit','Industriële afwerking','Schoner op de klus'],
        pl: ['Niska emisja LZO','Opcje 1K i 2K','Wiele podłoży','Korozyjność C1–C5','Wykańczanie przemysłowe','Czyściej w pracy'],
        ro: ['Emisii reduse de COV','Opțiuni 1K și 2K','Multi-substrat','Corozivitate C1–C5','Finisare industrială','Mai curat la lucru'],
        de: ['Niedrige VOC-Emissionen','1K- &amp; 2K-Optionen','Multi-Untergrund','C1–C5 Korrosivität','Industrieveredelung','Sauberer bei der Arbeit'],
        fr: ['Faibles émissions de COV','Options 1K &amp; 2K','Multi-supports','Corrosivité C1–C5','Finition industrielle','Plus propre sur le chantier'],
        es: ['Bajas emisiones de COV','Opciones 1K &amp; 2K','Multisustrato','Corrosividad C1–C5','Acabado industrial','Más limpio en obra'],
        it: ['Basse emissioni di COV','Opzioni 1K &amp; 2K','Multi-supporto','Corrosività C1–C5','Finitura industriale','Più pulito sul lavoro'],
        tr: ['Düşük VOC emisyonu','1K &amp; 2K seçenekleri','Çok yüzeyli','C1–C5 korozyon','Endüstriyel son kat','Sahada daha temiz'], no: ['Lave VOC-utslipp','1K- &amp; 2K-alternativer','Flere underlag','C1–C5 korrosivitet','Industriell finish','Renere på jobben'], sv: ['Låga VOC-utsläpp','1K- &amp; 2K-alternativ','Flera underlag','C1–C5 korrosivitet','Industriell finish','Renare på jobbet'] }],
      ['.bp-card span', {
        nl: ['Waterbasis vermindert vluchtige organische stoffen drastisch t.o.v. solventcoatings.','Een- en tweecomponentensystemen voor elke klus — van productafwerking tot staalbescherming.','Betrouwbare hechting op staal, aluminium en verzinkte oppervlakken.','Ontwikkeld voor alle atmosferische corrosiviteitsklassen C1 tot C5.','Een strakke, consistente afwerking voor OEM- en industriële productlijnen.','Minder solventlast betekent een gezondere werkplek en een lichtere voetafdruk.'],
        pl: ['Formuła wodna drastycznie redukuje lotne związki organiczne w porównaniu z powłokami rozpuszczalnikowymi.','Systemy jedno- i dwuskładnikowe do każdego zadania — od wykańczania produktów po ochronę stali.','Niezawodna przyczepność do stali, aluminium i powierzchni ocynkowanych.','Zaprojektowane dla klas korozyjności atmosferycznej od C1 do C5.','Czyste, jednolite wykończenie dla linii OEM i przemysłowych.','Mniejsze obciążenie rozpuszczalnikami to zdrowsze miejsce pracy i mniejszy ślad.'],
        ro: ['Formula pe bază de apă reduce drastic compușii organici volatili față de acoperirile cu solvenți.','Sisteme mono- și bicomponente pentru orice lucrare — de la finisarea produselor la protecția oțelului.','Aderență fiabilă pe oțel, aluminiu și suprafețe zincate.','Concepute pentru clasele de corozivitate atmosferică de la C1 la C5.','Un finisaj curat și uniform pentru liniile OEM și industriale.','Mai puțini solvenți înseamnă un loc de muncă mai sănătos și o amprentă mai mică.'],
        de: ['Die Wasserbasis senkt flüchtige organische Verbindungen drastisch gegenüber Lösemittelbeschichtungen.','Ein- und Zweikomponentensysteme für jede Aufgabe — von der Produktveredelung bis zum Stahlschutz.','Zuverlässige Haftung auf Stahl, Aluminium und verzinkten Oberflächen.','Entwickelt für alle atmosphärischen Korrosivitätsklassen von C1 bis C5.','Eine glatte, gleichmäßige Veredelung für OEM- und Industrieproduktlinien.','Weniger Lösemittel bedeutet einen gesünderen Arbeitsplatz und einen leichteren Fußabdruck.'],
        fr: ['La base aqueuse réduit drastiquement les composés organiques volatils par rapport aux revêtements solvantés.','Des systèmes mono- et bicomposants pour chaque chantier — de la finition de produits à la protection de l\'acier.','Une adhérence fiable sur l\'acier, l\'aluminium et les surfaces galvanisées.','Conçus pour toutes les classes de corrosivité atmosphérique de C1 à C5.','Une finition nette et homogène pour les lignes OEM et industrielles.','Moins de solvants, c\'est un lieu de travail plus sain et une empreinte allégée.'],
        es: ['La base acuosa reduce drásticamente los compuestos orgánicos volátiles frente a los recubrimientos con disolvente.','Sistemas mono y bicomponente para cada trabajo — desde el acabado de productos hasta la protección del acero.','Adherencia fiable sobre acero, aluminio y superficies galvanizadas.','Desarrollados para todas las clases de corrosividad atmosférica de C1 a C5.','Un acabado limpio y uniforme para líneas OEM e industriales.','Menos carga de disolvente significa un entorno de trabajo más sano y una huella más ligera.'],
        it: ['La base acqua riduce drasticamente i composti organici volatili rispetto ai rivestimenti a solvente.','Sistemi mono e bicomponente per ogni lavoro — dalla finitura dei prodotti alla protezione dell\'acciaio.','Adesione affidabile su acciaio, alluminio e superfici zincate.','Sviluppati per tutte le classi di corrosività atmosferica da C1 a C5.','Una finitura pulita e uniforme per le linee OEM e industriali.','Meno solventi significa un ambiente di lavoro più sano e un\'impronta più leggera.'],
        tr: ['Su bazı, solvent kaplamalara kıyasla uçucu organik bileşikleri büyük ölçüde azaltır.','Ürün son katından çelik korumasına kadar her iş için tek ve çift bileşenli sistemler.','Çelik, alüminyum ve galvanizli yüzeylerde güvenilir yapışma.','Tüm atmosferik korozyon sınıfları C1 ile C5 için geliştirildi.','OEM ve endüstriyel ürün hatları için pürüzsüz, tutarlı bir son kat.','Daha az solvent yükü, daha sağlıklı bir iş ortamı ve daha hafif bir ayak izi demektir.'], no: ['En vannbasis reduserer flyktige organiske forbindelser drastisk sammenlignet med løsemiddelbelegg.','En- og tokomponentsystemer for enhver jobb — fra produktfinish til stålbeskyttelse.','Pålitelig heft på stål, aluminium og galvaniserte overflater.','Utviklet for alle atmosfæriske korrosivitetsklasser C1 til C5.','En stram, konsistent finish for OEM- og industrielle produktlinjer.','Mindre løsemiddelbelastning betyr en sunnere arbeidsplass og et lettere fotavtrykk.'], sv: ['En vattenbas minskar flyktiga organiska föreningar drastiskt jämfört med lösningsmedelsbeläggningar.','En- och tvåkomponentssystem för varje jobb — från produktfinish till stålskydd.','Pålitlig vidhäftning på stål, aluminium och galvaniserade ytor.','Utvecklad för alla atmosfäriska korrosivitetsklasser C1 till C5.','En stram, konsekvent finish för OEM- och industriella produktlinjer.','Mindre lösningsmedelsbelastning betyder en hälsosammare arbetsplats och ett lättare fotavtryck.'] }],
      ['h2', {
        nl: ['Solventprestaties,<br><span class="bp-accent">waterchemie</span>','Vind het juiste Aquaran-systeem'],
        pl: ['Wydajność rozpuszczalnikowa,<br><span class="bp-accent">chemia wodna</span>','Znajdź właściwy system Aquaran'],
        ro: ['Performanță cu solvenți,<br><span class="bp-accent">chimie pe bază de apă</span>','Găsește sistemul Aquaran potrivit'],
        de: ['Lösemittelleistung,<br><span class="bp-accent">Wasserchemie</span>','Finden Sie das richtige Aquaran-System'],
        fr: ['Performance solvantée,<br><span class="bp-accent">chimie de l\'eau</span>','Trouvez le bon système Aquaran'],
        es: ['Rendimiento con disolvente,<br><span class="bp-accent">química del agua</span>','Encuentre el sistema Aquaran adecuado'],
        it: ['Prestazioni a solvente,<br><span class="bp-accent">chimica dell\'acqua</span>','Trova il sistema Aquaran giusto'],
        tr: ['Solvent performansı,<br><span class="bp-accent">su kimyası</span>','Doğru Aquaran sistemini bulun'], no: ['Løsemiddelytelse,<br><span class="bp-accent">vannkjemi</span>','Finn det riktige Aquaran-systemet'], sv: ['Lösningsmedelsprestanda,<br><span class="bp-accent">vattenkemi</span>','Hitta rätt Aquaran-system'] }],
      ['.bp-list span', {
        nl: ['Duurzaamheid en bescherming vergelijkbaar met traditionele solventcoatings.','Lagere emissies op de lijn en in de lucht, voor schonere productie.','Geschikt voor industriële productafwerking en bescherming van staalconstructies.'],
        pl: ['Trwałość i ochrona porównywalne z tradycyjnymi powłokami rozpuszczalnikowymi.','Niższe emisje na linii i w powietrzu, wspierające czystszą produkcję.','Odpowiednie do wykańczania produktów przemysłowych i ochrony konstrukcji stalowych.'],
        ro: ['Durabilitate și protecție comparabile cu acoperirile tradiționale cu solvenți.','Emisii mai reduse pe linie și în aer, pentru o producție mai curată.','Potrivite pentru finisarea produselor industriale și protecția construcțiilor din oțel.'],
        de: ['Haltbarkeit und Schutz vergleichbar mit herkömmlichen Lösemittelbeschichtungen.','Geringere Emissionen an der Linie und in der Luft, für eine sauberere Produktion.','Geeignet für die industrielle Produktveredelung und den Schutz von Stahlkonstruktionen.'],
        fr: ['Une durabilité et une protection comparables aux revêtements solvantés traditionnels.','Des émissions réduites sur la ligne et dans l\'air, pour une production plus propre.','Adapté à la finition de produits industriels et à la protection des structures en acier.'],
        es: ['Durabilidad y protección comparables a los recubrimientos tradicionales con disolvente.','Menores emisiones en la línea y en el aire, para una producción más limpia.','Apto para el acabado de productos industriales y la protección de estructuras de acero.'],
        it: ['Durabilità e protezione paragonabili ai rivestimenti tradizionali a solvente.','Emissioni più basse in linea e nell\'aria, per una produzione più pulita.','Adatto alla finitura di prodotti industriali e alla protezione di strutture in acciaio.'],
        tr: ['Geleneksel solvent kaplamalarla kıyaslanabilir dayanıklılık ve koruma.','Hatta ve havada daha düşük emisyon, daha temiz üretim için.','Endüstriyel ürün son katı ve çelik yapı koruması için uygun.'], no: ['Slitestyrke og beskyttelse sammenlignbar med tradisjonelle løsemiddelbelegg.','Lavere utslipp på linjen og i lufta, for renere produksjon.','Egnet for industriell produktfinish og beskyttelse av stålkonstruksjoner.'], sv: ['Hållbarhet och skydd jämförbart med traditionella lösningsmedelsbeläggningar.','Lägre utsläpp på linjen och i luften, för renare produktion.','Lämplig för industriell produktfinish och skydd av stålkonstruktioner.'] }],
      ['.bp-stat .l', {
        nl: ['VOS-emissies t.o.v. solventbasis','Atmosferische corrosiviteitsklassen','Een- en tweecomponentensystemen','Waterbasis van origine'],
        pl: ['Emisja LZO vs. rozpuszczalnikowe','Klasy korozyjności atmosferycznej','Systemy jedno- i dwuskładnikowe','Na bazie wody z założenia'],
        ro: ['Emisii COV vs. pe bază de solvenți','Clase de corozivitate atmosferică','Sisteme mono- și bicomponente','Pe bază de apă din concepție'],
        de: ['VOC-Emissionen ggü. Lösemittelbasis','Atmosphärische Korrosivitätsklassen','Ein- und Zweikomponentensysteme','Wasserbasiert von Grund auf'],
        fr: ['Émissions de COV vs base solvantée','Classes de corrosivité atmosphérique','Systèmes mono et bicomposants','À base d\'eau dès l\'origine'],
        es: ['Emisiones de COV frente a base disolvente','Clases de corrosividad atmosférica','Sistemas mono y bicomponente','Al agua desde su concepción'],
        it: ['Emissioni di COV vs base solvente','Classi di corrosività atmosferica','Sistemi mono e bicomponente','A base acqua per concezione'],
        tr: ['Solvent bazına karşı VOC emisyonu','Atmosferik korozyon sınıfları','Tek ve çift bileşenli sistemler','Doğası gereği su bazlı'], no: ['VOC-utslipp vs løsemiddelbasis','Atmosfæriske korrosivitetsklasser','En- og tokomponentsystemer','Vannbasert fra opprinnelsen'], sv: ['VOC-utsläpp vs lösningsmedelsbas','Atmosfäriska korrosivitetsklasser','En- och tvåkomponentssystem','Vattenbaserad från grunden'] }],
      ['.bp-band p', {
        nl: 'Ontdek het volledige Aquaran-assortiment in de Baril Coatings-catalogus — met datasheets en veiligheidsbladen — of praat met onze coatingexperts.',
        pl: 'Poznaj pełną gamę Aquaran w katalogu Baril Coatings — z kartami technicznymi i charakterystykami — lub porozmawiaj z naszymi ekspertami.',
        ro: 'Explorează întreaga gamă Aquaran în catalogul Baril Coatings — cu fișe tehnice și de securitate — sau discută cu experții noștri.',
        de: 'Entdecken Sie das gesamte Aquaran-Sortiment im Baril Coatings-Katalog — mit Datenblättern und Sicherheitsdatenblättern — oder sprechen Sie mit unseren Beschichtungsexperten.',
        fr: 'Découvrez toute la gamme Aquaran dans le catalogue Baril Coatings — avec fiches techniques et de sécurité — ou parlez à nos experts en revêtements.',
        es: 'Descubra toda la gama Aquaran en el catálogo de Baril Coatings — con fichas técnicas y de seguridad — o hable con nuestros expertos en recubrimientos.',
        it: 'Scopri l\'intera gamma Aquaran nel catalogo Baril Coatings — con schede tecniche e di sicurezza — o parla con i nostri esperti di rivestimenti.',
        tr: 'Aquaran serisinin tamamını Baril Coatings kataloğunda keşfedin — teknik ve güvenlik veri sayfalarıyla — ya da kaplama uzmanlarımızla konuşun.', no: 'Oppdag hele Aquaran-sortimentet i Baril Coatings-katalogen — med datablad og sikkerhetsdatablad — eller snakk med coatingekspertene våre.', sv: 'Upptäck hela Aquaran-sortimentet i Baril Coatings-katalogen — med datablad och säkerhetsdatablad — eller prata med våra beläggningsexperter.' }],
      ['.foot-claim', {
        nl: '<span class="bp-accent">Aquaran</span> — watergedragen beschermende coatings.',
        pl: '<span class="bp-accent">Aquaran</span> — wodorozcieńczalne powłoki ochronne.',
        ro: '<span class="bp-accent">Aquaran</span> — acoperiri de protecție pe bază de apă.',
        de: '<span class="bp-accent">Aquaran</span> — wasserbasierte Schutzbeschichtungen.',
        fr: '<span class="bp-accent">Aquaran</span> — revêtements de protection à base d\'eau.',
        es: '<span class="bp-accent">Aquaran</span> — recubrimientos protectores al agua.',
        it: '<span class="bp-accent">Aquaran</span> — rivestimenti protettivi a base acqua.',
        tr: '<span class="bp-accent">Aquaran</span> — su bazlı koruyucu kaplamalar.', no: '<span class="bp-accent">Aquaran</span> — vannbaserte beskyttende belegg.', sv: '<span class="bp-accent">Aquaran</span> — vattenburna skyddande beläggningar.' }]
    ],

    dualcure: [
      ['.bp-tag', { nl: 'Dual-cure-technologie · deels biobased', pl: 'Technologia podwójnego utwardzania · częściowo biobazowa', ro: 'Tehnologie cu întărire dublă · parțial biobazată', de: 'Dual-Cure-Technologie · teils biobasiert', fr: 'Technologie dual-cure · partiellement biosourcée', es: 'Tecnología dual-cure · parcialmente de base biológica', it: 'Tecnologia dual-cure · parzialmente biobased', tr: 'Dual-cure teknolojisi · kısmen biyobazlı', no: 'Dual-cure-teknologi · delvis biobasert', sv: 'Dual-cure-teknik · delvis biobaserad' }],
      ['.bp-sub', {
        nl: 'Een gepatenteerde dual-cure-technologie — de chemische 2K-reactie <strong>plus</strong> een vocht-gedreven uitharding, verweven tot één dichte moleculaire structuur. Levenslange bescherming, in één dag aangebracht.',
        pl: 'Opatentowana technologia podwójnego utwardzania — reakcja chemiczna 2K <strong>oraz</strong> utwardzanie wilgocią, splecione w jedną gęstą sieć molekularną. Ochrona na całe życie, nakładana w jeden dzień.',
        ro: 'O tehnologie patentată cu întărire dublă — reacția chimică 2K <strong>plus</strong> o întărire prin umiditate, împletite într-o singură rețea moleculară densă. Protecție pe toată durata de viață, aplicată într-o singură zi.',
        de: 'Eine patentierte Dual-Cure-Technologie — die chemische 2K-Reaktion <strong>plus</strong> eine feuchtigkeitsgesteuerte Härtung, verwoben zu einer dichten molekularen Struktur. Lebenslanger Schutz, an einem Tag aufgetragen.',
        fr: 'Une technologie dual-cure brevetée — la réaction chimique 2K <strong>plus</strong> un durcissement piloté par l\'humidité, tissés en une seule structure moléculaire dense. Une protection à vie, appliquée en une journée.',
        es: 'Una tecnología dual-cure patentada — la reacción química 2K <strong>más</strong> un curado impulsado por la humedad, entrelazados en una única estructura molecular densa. Protección de por vida, aplicada en un solo día.',
        it: 'Una tecnologia dual-cure brevettata — la reazione chimica 2K <strong>più</strong> un indurimento guidato dall\'umidità, intrecciati in un\'unica struttura molecolare densa. Protezione a vita, applicata in un solo giorno.',
        tr: 'Patentli bir dual-cure teknolojisi — 2K kimyasal reaksiyonu <strong>artı</strong> nemle tetiklenen bir kürlenme, tek bir yoğun moleküler yapıda iç içe örülmüş. Bir günde uygulanan, ömür boyu koruma.', no: 'En patentert dual-cure-teknologi — den kjemiske 2K-reaksjonen <strong>pluss</strong> en fuktdrevet herding, vevd sammen til én tett molekylær struktur. Livslang beskyttelse, påført på én dag.', sv: 'En patenterad dual-cure-teknik — den kemiska 2K-reaktionen <strong>plus</strong> en fuktdriven härdning, sammanvävda till en tät molekylär struktur. Livslångt skydd, applicerat på en dag.' }],
      ['.bp-quick span', {
        nl: ['<b>2K + vocht</b>-uitharding','Tot <b>60% dunner</b>','<b>2 lagen / 1 dag</b>','<b>NORSOK</b>-gecertificeerd'],
        pl: ['Utwardzanie <b>2K + wilgoć</b>','Do <b>60% cieńsze</b>','<b>2 warstwy / 1 dzień</b>','Certyfikat <b>NORSOK</b>'],
        ro: ['Întărire <b>2K + umiditate</b>','Cu până la <b>60% mai subțire</b>','<b>2 straturi / 1 zi</b>','Certificat <b>NORSOK</b>'],
        de: ['<b>2K + Feuchte</b>-Härtung','Bis zu <b>60% dünner</b>','<b>2 Schichten / 1 Tag</b>','<b>NORSOK</b>-zertifiziert'],
        fr: ['Durcissement <b>2K + humidité</b>','Jusqu\'à <b>60% plus fin</b>','<b>2 couches / 1 jour</b>','Certifié <b>NORSOK</b>'],
        es: ['Curado <b>2K + humedad</b>','Hasta <b>60% más fino</b>','<b>2 capas / 1 día</b>','Certificado <b>NORSOK</b>'],
        it: ['Indurimento <b>2K + umidità</b>','Fino al <b>60% più sottile</b>','<b>2 strati / 1 giorno</b>','Certificato <b>NORSOK</b>'],
        tr: ['<b>2K + nem</b> kürlenmesi','<b>%60\'a kadar daha ince</b>','<b>2 kat / 1 gün</b>','<b>NORSOK</b> sertifikalı'], no: ['<b>2K + fukt</b>-herding','Inntil <b>60% tynnere</b>','<b>2 strøk / 1 dag</b>','<b>NORSOK</b>-sertifisert'], sv: ['<b>2K + fukt</b>-härdning','Upp till <b>60% tunnare</b>','<b>2 lager / 1 dag</b>','<b>NORSOK</b>-certifierad'] }],
      ['.eyebrow', { nl: ['Waarom DualCure','De chemie'], pl: ['Dlaczego DualCure','Chemia'], ro: ['De ce DualCure','Chimia'], de: ['Warum DualCure','Die Chemie'], fr: ['Pourquoi DualCure','La chimie'], es: ['Por qué DualCure','La química'], it: ['Perché DualCure','La chimica'], tr: ['Neden DualCure','Kimyası'], no: ['Hvorfor DualCure','Kjemien'], sv: ['Varför DualCure','Kemin'] }],
      ['.bp-quote', {
        nl: 'De meeste coatings harden op één manier uit. DualCure hardt op twee manieren tegelijk uit — de 2K-chemie van componenten A en B, <em>plus</em> een vochtuitharding uit de lucht. Twee netwerken verweven tot één uitzonderlijk dichte structuur: sterkere bindingen, meer flexibiliteit, veel minder coating.',
        pl: 'Większość powłok utwardza się w jeden sposób. DualCure utwardza się na dwa sposoby naraz — chemia 2K składników A i B <em>oraz</em> utwardzanie wilgocią z powietrza. Dwie sieci splatają się w jedną wyjątkowo gęstą strukturę: mocniejsze wiązania, większa elastyczność, znacznie mniej powłoki.',
        ro: 'Majoritatea acoperirilor se întăresc într-un singur mod. DualCure se întărește în două moduri simultan — chimia 2K a componentelor A și B <em>plus</em> o întărire prin umiditatea din aer. Două rețele se împletesc într-o structură excepțional de densă: legături mai strânse, mai multă flexibilitate, mult mai puțină acoperire.',
        de: 'Die meisten Beschichtungen härten auf eine Weise aus. DualCure härtet auf zwei Arten gleichzeitig aus — die 2K-Chemie der Komponenten A und B, <em>plus</em> eine Feuchtigkeitshärtung aus der Luft. Zwei Netzwerke verweben sich zu einer außergewöhnlich dichten Struktur: stärkere Bindungen, mehr Flexibilität, viel weniger Beschichtung.',
        fr: 'La plupart des revêtements durcissent d\'une seule manière. DualCure durcit de deux manières à la fois — la chimie 2K des composants A et B, <em>plus</em> un durcissement par l\'humidité de l\'air. Deux réseaux se tissent en une structure exceptionnellement dense : des liaisons plus fortes, plus de flexibilité, bien moins de revêtement.',
        es: 'La mayoría de los recubrimientos curan de una sola forma. DualCure cura de dos formas a la vez — la química 2K de los componentes A y B, <em>más</em> un curado por la humedad del aire. Dos redes se entrelazan en una estructura excepcionalmente densa: enlaces más fuertes, más flexibilidad, mucho menos recubrimiento.',
        it: 'La maggior parte dei rivestimenti indurisce in un solo modo. DualCure indurisce in due modi contemporaneamente — la chimica 2K dei componenti A e B, <em>più</em> un indurimento dall\'umidità dell\'aria. Due reti si intrecciano in una struttura eccezionalmente densa: legami più forti, maggiore flessibilità, molto meno rivestimento.',
        tr: 'Çoğu kaplama tek bir şekilde kürlenir. DualCure aynı anda iki şekilde kürlenir — A ve B bileşenlerinin 2K kimyası, <em>artı</em> havadaki nemden gelen bir kürlenme. İki ağ, olağanüstü yoğun tek bir yapıda iç içe örülür: daha güçlü bağlar, daha fazla esneklik, çok daha az kaplama.', no: 'De fleste belegg herder på én måte. DualCure herder på to måter samtidig — 2K-kjemien fra komponent A og B, <em>pluss</em> en fuktherding fra lufta. To nettverk vevd sammen til én usedvanlig tett struktur: sterkere bindinger, mer fleksibilitet, langt mindre belegg.', sv: 'De flesta beläggningar härdar på ett sätt. DualCure härdar på två sätt samtidigt — 2K-kemin från komponent A och B, <em>plus</em> en fukthärdning från luften. Två nätverk sammanvävda till en exceptionellt tät struktur: starkare bindningar, mer flexibilitet, långt mindre beläggning.' }],
      ['.bp-card b', {
        nl: ['Twee uithardingen, één netwerk','Tot 60% dunner','Twee lagen in één dag','25 jaar+ in C5','NORSOK-gecertificeerd','Lagere CO₂ &amp; VOS'],
        pl: ['Dwa utwardzania, jedna sieć','Do 60% cieńsze','Dwie warstwy w jeden dzień','25 lat+ w C5','Certyfikat NORSOK','Niższe CO₂ i LZO'],
        ro: ['Două întăriri, o rețea','Cu până la 60% mai subțire','Două straturi într-o zi','25 ani+ în C5','Certificat NORSOK','CO₂ și COV mai reduse'],
        de: ['Zwei Härtungen, ein Netzwerk','Bis zu 60% dünner','Zwei Schichten an einem Tag','25 Jahre+ in C5','NORSOK-zertifiziert','Geringere CO₂ &amp; VOC'],
        fr: ['Deux durcissements, un réseau','Jusqu\'à 60% plus fin','Deux couches en un jour','25 ans+ en C5','Certifié NORSOK','CO₂ &amp; COV réduits'],
        es: ['Dos curados, una red','Hasta 60% más fino','Dos capas en un día','25 años+ en C5','Certificado NORSOK','Menos CO₂ &amp; COV'],
        it: ['Due induramenti, una rete','Fino al 60% più sottile','Due strati in un giorno','25 anni+ in C5','Certificato NORSOK','CO₂ &amp; COV ridotti'],
        tr: ['İki kürlenme, tek ağ','%60\'a kadar daha ince','Bir günde iki kat','C5\'te 25 yıl+','NORSOK sertifikalı','Daha düşük CO₂ &amp; VOC'], no: ['To herdinger, ett nettverk','Inntil 60% tynnere','To strøk på én dag','25 år+ i C5','NORSOK-sertifisert','Lavere CO₂ &amp; VOC'], sv: ['Två härdningar, ett nätverk','Upp till 60% tunnare','Två lager på en dag','25 år+ i C5','NORSOK-certifierad','Lägre CO₂ &amp; VOC'] }],
      ['.bp-card span', {
        nl: ['2K-chemie en vochtuitharding verweven tot één uitzonderlijk dichte structuur.','Dunne-laag-technologie beschermt met een fractie van de conventionele laagdikte.','Ultrasnelle doorharding: twee lagen in één werkdag.','Minimaal 25 jaar bescherming in C5-omgevingen bij 200 μm totale dikte.','Gecertificeerde systemen voor de zwaarste marine- en offshore-omstandigheden.','Minder coating, geen extra warmte nodig, deels biobased — een lichtere voetafdruk.'],
        pl: ['Chemia 2K i utwardzanie wilgocią splatają się w jedną, wyjątkowo gęstą sieć.','Technologia cienkowarstwowa chroni przy ułamku konwencjonalnej grubości.','Bardzo szybkie utwardzanie pozwala nałożyć dwie warstwy w jeden dzień roboczy.','Minimum 25 lat ochrony w środowiskach C5 przy łącznej grubości 200 μm.','Certyfikowane systemy do najcięższych warunków morskich i offshore.','Mniej powłoki, bez dodatkowego ciepła, częściowo biobazowa — mniejszy ślad.'],
        ro: ['Chimia 2K și întărirea prin umiditate se împletesc într-o singură rețea, excepțional de densă.','Tehnologia în strat subțire protejează cu o fracțiune din grosimea convențională.','Întărirea ultrarapidă permite aplicarea a două straturi într-o singură zi de lucru.','Minimum 25 de ani de protecție în medii C5 la 200 μm grosime totală.','Sisteme certificate pentru cele mai dure condiții maritime și offshore.','Mai puțină acoperire, fără căldură suplimentară, parțial biobazată — o amprentă mai mică.'],
        de: ['2K-Chemie und Feuchtigkeitshärtung verweben sich zu einer außergewöhnlich dichten Struktur.','Die Dünnschichttechnologie schützt mit einem Bruchteil der konventionellen Schichtdicke.','Ultraschnelle Durchhärtung: zwei Schichten an einem Arbeitstag.','Mindestens 25 Jahre Schutz in C5-Umgebungen bei 200 μm Gesamtdicke.','Zertifizierte Systeme für die härtesten maritimen und Offshore-Bedingungen.','Weniger Beschichtung, keine zusätzliche Wärme nötig, teils biobasiert — ein leichterer Fußabdruck.'],
        fr: ['La chimie 2K et le durcissement par l\'humidité se tissent en une structure exceptionnellement dense.','La technologie en couche mince protège avec une fraction de l\'épaisseur conventionnelle.','Un durcissement ultrarapide : deux couches en une seule journée de travail.','Au moins 25 ans de protection en environnement C5 à 200 μm d\'épaisseur totale.','Des systèmes certifiés pour les conditions marines et offshore les plus rudes.','Moins de revêtement, aucune chaleur supplémentaire, partiellement biosourcé — une empreinte allégée.'],
        es: ['La química 2K y el curado por humedad se entrelazan en una estructura excepcionalmente densa.','La tecnología de capa fina protege con una fracción del espesor convencional.','Curado ultrarrápido: dos capas en una sola jornada de trabajo.','Mínimo 25 años de protección en entornos C5 a 200 μm de espesor total.','Sistemas certificados para las condiciones marinas y offshore más exigentes.','Menos recubrimiento, sin calor adicional, parcialmente de base biológica — una huella más ligera.'],
        it: ['La chimica 2K e l\'indurimento dall\'umidità si intrecciano in una struttura eccezionalmente densa.','La tecnologia a film sottile protegge con una frazione dello spessore convenzionale.','Indurimento ultrarapido: due strati in una sola giornata lavorativa.','Almeno 25 anni di protezione in ambienti C5 a 200 μm di spessore totale.','Sistemi certificati per le condizioni marine e offshore più severe.','Meno rivestimento, nessun calore aggiuntivo, parzialmente biobased — un\'impronta più leggera.'],
        tr: ['2K kimyası ve nem kürlenmesi, olağanüstü yoğun tek bir yapıda iç içe örülür.','İnce film teknolojisi, geleneksel kalınlığın küçük bir kısmıyla korur.','Ultra hızlı kürlenme: tek bir iş gününde iki kat.','C5 ortamlarında 200 μm toplam kalınlıkta en az 25 yıl koruma.','En zorlu deniz ve açık deniz koşulları için sertifikalı sistemler.','Daha az kaplama, ek ısı gerektirmez, kısmen biyobazlı — daha hafif bir ayak izi.'], no: ['2K-kjemi og fuktherding vevd sammen til én usedvanlig tett struktur.','Tynnsjikt-teknologi beskytter med en brøkdel av konvensjonell filmtykkelse.','Ultrarask gjennomherding: to strøk på én arbeidsdag.','Minimum 25 års beskyttelse i C5-miljøer ved 200 μm total tykkelse.','Sertifiserte systemer for de tøffeste marine- og offshore-forholdene.','Mindre belegg, ingen tilført varme nødvendig, delvis biobasert — et lettere fotavtrykk.'], sv: ['2K-kemi och fukthärdning sammanvävda till en exceptionellt tät struktur.','Tunnskiktsteknik skyddar med en bråkdel av konventionell filmtjocklek.','Ultrasnabb genomhärdning: två lager på en arbetsdag.','Minst 25 års skydd i C5-miljöer vid 200 μm total tjocklek.','Certifierade system för de tuffaste marin- och offshore-förhållandena.','Mindre beläggning, ingen tillförd värme behövs, delvis biobaserad — ett lättare fotavtryck.'] }],
      ['h2', {
        nl: ['Eén netwerk,<br><span class="bp-accent">dubbel uitgehard</span>','Kies DualCure'],
        pl: ['Jedna sieć,<br><span class="bp-accent">podwójnie utwardzona</span>','Wybierz DualCure'],
        ro: ['O singură rețea,<br><span class="bp-accent">întărită dublu</span>','Specifică DualCure'],
        de: ['Ein Netzwerk,<br><span class="bp-accent">doppelt gehärtet</span>','DualCure wählen'],
        fr: ['Un réseau,<br><span class="bp-accent">doublement durci</span>','Choisir DualCure'],
        es: ['Una red,<br><span class="bp-accent">doblemente curada</span>','Elija DualCure'],
        it: ['Una rete,<br><span class="bp-accent">a doppio indurimento</span>','Scegli DualCure'],
        tr: ['Tek ağ,<br><span class="bp-accent">çift kürlenmiş</span>','DualCure\'u seçin'], no: ['Ett nettverk,<br><span class="bp-accent">dobbeltherdet</span>','Velg DualCure'], sv: ['Ett nätverk,<br><span class="bp-accent">dubbelhärdat</span>','Välj DualCure'] }],
      ['.bp-list span', {
        nl: ['Koud uithardend: hardt uit door een vochtreactie uit de lucht — geen extra warmte of energie.','Dichte moleculaire structuur voor sterke hechting en blijvende flexibiliteit.','Levenslange bescherming over de volledige economische levensduur van het object.'],
        pl: ['Utwardzanie na zimno: utwardza się dzięki reakcji z wilgocią z powietrza — bez dodatkowego ciepła i energii.','Gęsta struktura molekularna dla mocnej przyczepności i trwałej elastyczności.','Ochrona na całe życie przez pełny okres eksploatacji obiektu.'],
        ro: ['Întărire la rece: se întărește printr-o reacție cu umiditatea din aer — fără căldură sau energie suplimentară.','Structură moleculară densă pentru aderență puternică și flexibilitate durabilă.','Protecție pe toată durata de viață economică a activului.'],
        de: ['Kalthärtend: härtet durch eine Feuchtigkeitsreaktion aus der Luft aus — ohne zusätzliche Wärme oder Energie.','Dichte molekulare Struktur für starke Haftung und dauerhafte Flexibilität.','Lebenslanger Schutz über die gesamte wirtschaftliche Lebensdauer des Objekts.'],
        fr: ['Durcissement à froid : durcit par une réaction à l\'humidité de l\'air — sans chaleur ni énergie supplémentaires.','Une structure moléculaire dense pour une forte adhérence et une flexibilité durable.','Une protection à vie sur toute la durée de vie économique de l\'ouvrage.'],
        es: ['Curado en frío: cura mediante una reacción con la humedad del aire — sin calor ni energía adicionales.','Estructura molecular densa para una fuerte adherencia y una flexibilidad duradera.','Protección de por vida durante toda la vida económica del activo.'],
        it: ['Indurimento a freddo: indurisce grazie a una reazione con l\'umidità dell\'aria — senza calore o energia aggiuntivi.','Struttura molecolare densa per una forte adesione e una flessibilità duratura.','Protezione a vita per l\'intera vita economica dell\'opera.'],
        tr: ['Soğuk kürlenme: havadaki nemle bir reaksiyon sayesinde kürlenir — ek ısı veya enerji gerekmez.','Güçlü yapışma ve kalıcı esneklik için yoğun moleküler yapı.','Yapının tüm ekonomik ömrü boyunca ömür boyu koruma.'], no: ['Kaldherdende: herder gjennom en fuktreaksjon fra lufta — ingen tilført varme eller energi.','Tett molekylær struktur for sterk heft og varig fleksibilitet.','Livslang beskyttelse over objektets fulle økonomiske levetid.'], sv: ['Kallhärdande: härdar genom en fuktreaktion från luften — ingen tillförd värme eller energi.','Tät molekylär struktur för stark vidhäftning och bestående flexibilitet.','Livslångt skydd över tillgångens hela ekonomiska livslängd.'] }],
      ['.bp-stat .l', {
        nl: ['Dunner dan conventionele coatings','Twee lagen in één dag aangebracht','Minimale bescherming in C5','Gecertificeerde offshore-systemen'],
        pl: ['Cieńsze niż konwencjonalne powłoki','Dwie warstwy nałożone w jeden dzień','Minimalna ochrona w C5','Certyfikowane systemy offshore'],
        ro: ['Mai subțire decât acoperirile convenționale','Două straturi aplicate într-o zi','Protecție minimă în C5','Sisteme offshore certificate'],
        de: ['Dünner als konventionelle Beschichtungen','Zwei Schichten an einem Tag aufgetragen','Mindestschutz in C5','Zertifizierte Offshore-Systeme'],
        fr: ['Plus fin que les revêtements conventionnels','Deux couches appliquées en un jour','Protection minimale en C5','Systèmes offshore certifiés'],
        es: ['Más fino que los recubrimientos convencionales','Dos capas aplicadas en un día','Protección mínima en C5','Sistemas offshore certificados'],
        it: ['Più sottile dei rivestimenti convenzionali','Due strati applicati in un giorno','Protezione minima in C5','Sistemi offshore certificati'],
        tr: ['Geleneksel kaplamalardan daha ince','Bir günde uygulanan iki kat','C5\'te minimum koruma','Sertifikalı açık deniz sistemleri'], no: ['Tynnere enn konvensjonelle belegg','To strøk påført på én dag','Minimum beskyttelse i C5','Sertifiserte offshore-systemer'], sv: ['Tunnare än konventionella beläggningar','Två lager applicerade på en dag','Minsta skydd i C5','Certifierade offshore-system'] }],
      ['.bp-band p', {
        nl: 'Ontdek het DualCure-assortiment in de Baril Coatings-catalogus — met datasheets en veiligheidsbladen — of bespreek je specificatie met onze coatingexperts.',
        pl: 'Poznaj gamę DualCure w katalogu Baril Coatings — z kartami technicznymi i charakterystykami — lub omów swoją specyfikację z naszymi ekspertami.',
        ro: 'Explorează gama DualCure în catalogul Baril Coatings — cu fișe tehnice și de securitate — sau discută specificația ta cu experții noștri.',
        de: 'Entdecken Sie das DualCure-Sortiment im Baril Coatings-Katalog — mit Datenblättern und Sicherheitsdatenblättern — oder besprechen Sie Ihre Spezifikation mit unseren Beschichtungsexperten.',
        fr: 'Découvrez la gamme DualCure dans le catalogue Baril Coatings — avec fiches techniques et de sécurité — ou discutez de votre spécification avec nos experts en revêtements.',
        es: 'Descubra la gama DualCure en el catálogo de Baril Coatings — con fichas técnicas y de seguridad — o comente su especificación con nuestros expertos en recubrimientos.',
        it: 'Scopri la gamma DualCure nel catalogo Baril Coatings — con schede tecniche e di sicurezza — o discuti la tua specifica con i nostri esperti di rivestimenti.',
        tr: 'DualCure serisini Baril Coatings kataloğunda keşfedin — teknik ve güvenlik veri sayfalarıyla — ya da şartnamenizi kaplama uzmanlarımızla görüşün.', no: 'Oppdag DualCure-sortimentet i Baril Coatings-katalogen — med datablad og sikkerhetsdatablad — eller diskuter spesifikasjonen din med coatingekspertene våre.', sv: 'Upptäck DualCure-sortimentet i Baril Coatings-katalogen — med datablad och säkerhetsdatablad — eller diskutera din specifikation med våra beläggningsexperter.' }],
      ['.foot-claim', {
        nl: '<span class="bp-accent">DualCure</span> — dual-cure beschermtechnologie.',
        pl: '<span class="bp-accent">DualCure</span> — technologia ochronna podwójnego utwardzania.',
        ro: '<span class="bp-accent">DualCure</span> — tehnologie de protecție cu întărire dublă.',
        de: '<span class="bp-accent">DualCure</span> — Dual-Cure-Schutztechnologie.',
        fr: '<span class="bp-accent">DualCure</span> — technologie de protection dual-cure.',
        es: '<span class="bp-accent">DualCure</span> — tecnología de protección dual-cure.',
        it: '<span class="bp-accent">DualCure</span> — tecnologia di protezione dual-cure.',
        tr: '<span class="bp-accent">DualCure</span> — dual-cure koruma teknolojisi.', no: '<span class="bp-accent">DualCure</span> — dual-cure beskyttelsesteknologi.', sv: '<span class="bp-accent">DualCure</span> — dual-cure skyddsteknik.' }]
    ],

    steelkote: [
      ['.bp-tag', { nl: 'Heavy-duty beschermende coatings', pl: 'Wytrzymałe powłoki ochronne', ro: 'Acoperiri de protecție de mare rezistență', de: 'Hochleistungs-Schutzbeschichtungen', fr: 'Revêtements de protection haute résistance', es: 'Recubrimientos protectores de alta resistencia', it: 'Rivestimenti protettivi heavy-duty', tr: 'Ağır hizmet koruyucu kaplamalar', no: 'Heavy-duty beskyttende belegg', sv: 'Heavy-duty skyddande beläggningar' }],
      ['.bp-sub', {
        nl: 'Drie decennia bewezen staalbescherming — epoxyprimers en urethaan toplagen ontwikkeld voor <strong>extreme corrosiebestendigheid</strong>, nu op weg naar volledig hernieuwbaar.',
        pl: 'Trzy dekady sprawdzonej ochrony stali — podkłady epoksydowe i nawierzchnie uretanowe zaprojektowane dla <strong>ekstremalnej odporności na korozję</strong>, teraz na drodze ku pełnej odnawialności.',
        ro: 'Trei decenii de protecție dovedită a oțelului — grunduri epoxidice și straturi de finisare uretanice concepute pentru <strong>rezistență extremă la coroziune</strong>, acum pe drumul către surse complet regenerabile.',
        de: 'Drei Jahrzehnte bewährter Stahlschutz — Epoxidgrundierungen und Urethan-Decklacke, entwickelt für <strong>extreme Korrosionsbeständigkeit</strong>, jetzt auf dem Weg zu vollständig erneuerbar.',
        fr: 'Trois décennies de protection de l\'acier éprouvée — des primaires époxy et des couches de finition uréthane conçus pour une <strong>résistance extrême à la corrosion</strong>, désormais en route vers le 100% renouvelable.',
        es: 'Tres décadas de protección del acero probada — imprimaciones epoxi y capas de acabado de uretano desarrolladas para una <strong>resistencia extrema a la corrosión</strong>, ahora en camino hacia lo totalmente renovable.',
        it: 'Tre decenni di protezione dell\'acciaio comprovata — primer epossidici e strati di finitura uretanici sviluppati per una <strong>resistenza estrema alla corrosione</strong>, ora in cammino verso il pienamente rinnovabile.',
        tr: 'Otuz yıllık kanıtlanmış çelik koruması — <strong>aşırı korozyon direnci</strong> için geliştirilmiş epoksi astarlar ve üretan son katlar, şimdi tamamen yenilenebilir olmaya doğru ilerliyor.', no: 'Tre tiår med bevist stålbeskyttelse — epoksy-primere og uretantopplag utviklet for <strong>ekstrem korrosjonsbestandighet</strong>, nå på vei mot fullt fornybar.', sv: 'Tre decennier av beprövat stålskydd — epoxiprimers och uretantopplager utvecklade för <strong>extrem korrosionsbeständighet</strong>, nu på väg mot helt förnybar.' }],
      ['.bp-quick span', {
        nl: ['<b>ISO 12944</b> alle klassen','<b>NORSOK</b>-gecertificeerd','Tot <b>25 jr</b> intervallen','<b>40% dunnere</b> lagen'],
        pl: ['<b>ISO 12944</b> wszystkie klasy','Certyfikat <b>NORSOK</b>','Do <b>25 lat</b> interwałów','<b>40% cieńsze</b> warstwy'],
        ro: ['<b>ISO 12944</b> toate clasele','Certificat <b>NORSOK</b>','Intervale de până la <b>25 ani</b>','Straturi <b>cu 40% mai subțiri</b>'],
        de: ['<b>ISO 12944</b> alle Klassen','<b>NORSOK</b>-zertifiziert','Bis zu <b>25 J.</b> Intervalle','<b>40% dünnere</b> Schichten'],
        fr: ['<b>ISO 12944</b> toutes classes','Certifié <b>NORSOK</b>','Intervalles jusqu\'à <b>25 ans</b>','Couches <b>40% plus fines</b>'],
        es: ['<b>ISO 12944</b> todas las clases','Certificado <b>NORSOK</b>','Intervalos de hasta <b>25 años</b>','Capas <b>40% más finas</b>'],
        it: ['<b>ISO 12944</b> tutte le classi','Certificato <b>NORSOK</b>','Intervalli fino a <b>25 anni</b>','Strati <b>40% più sottili</b>'],
        tr: ['<b>ISO 12944</b> tüm sınıflar','<b>NORSOK</b> sertifikalı','<b>25 yıla</b> kadar aralık','<b>%40 daha ince</b> katlar'], no: ['<b>ISO 12944</b> alle klasser','<b>NORSOK</b>-sertifisert','Inntil <b>25 år</b> intervaller','<b>40% tynnere</b> lag'], sv: ['<b>ISO 12944</b> alla klasser','<b>NORSOK</b>-certifierad','Upp till <b>25 år</b> intervall','<b>40% tunnare</b> lager'] }],
      ['.eyebrow', { nl: ['Waarom SteelKote','Gebouwd om te blijven'], pl: ['Dlaczego SteelKote','Stworzone, by trwać'], ro: ['De ce SteelKote','Construit să dureze'], de: ['Warum SteelKote','Gebaut, um zu bleiben'], fr: ['Pourquoi SteelKote','Conçu pour durer'], es: ['Por qué SteelKote','Hecho para perdurar'], it: ['Perché SteelKote','Costruito per durare'], tr: ['Neden SteelKote','Kalıcı olmak için yapıldı'], no: ['Hvorfor SteelKote','Bygget for å bli'], sv: ['Varför SteelKote','Byggd för att stanna'] }],
      ['.bp-quote', {
        nl: 'Al <em>30 jaar</em> bewezen in de zwaarste atmosferen — en nog steeds in ontwikkeling. SteelKote brengt extreme corrosiebescherming met lange intervallen naar staal en infrastructuur, in dunnere, slimmere lagen, op weg naar 100% hernieuwbaar.',
        pl: 'Sprawdzone w najtrudniejszych atmosferach od <em>30 lat</em> — i wciąż się rozwija. SteelKote zapewnia ekstremalną, długointerwałową ochronę antykorozyjną stali i infrastruktury, w cieńszych, inteligentniejszych warstwach, na drodze ku 100% odnawialności.',
        ro: 'Dovedit în cele mai dure atmosfere de <em>30 de ani</em> — și încă în evoluție. SteelKote aduce o protecție anticorozivă extremă, cu intervale lungi, pentru oțel și infrastructură, în straturi mai subțiri și mai inteligente, pe drumul către 100% regenerabil.',
        de: 'Seit <em>30 Jahren</em> in den härtesten Atmosphären bewährt — und noch immer in Entwicklung. SteelKote bringt extremen Korrosionsschutz mit langen Intervallen auf Stahl und Infrastruktur, in dünneren, intelligenteren Schichten, auf dem Weg zu 100% erneuerbar.',
        fr: 'Éprouvé dans les atmosphères les plus rudes depuis <em>30 ans</em> — et toujours en évolution. SteelKote apporte une protection anticorrosion extrême à intervalles longs à l\'acier et aux infrastructures, en couches plus fines et plus intelligentes, en route vers le 100% renouvelable.',
        es: 'Probado en las atmósferas más duras desde hace <em>30 años</em> — y en constante evolución. SteelKote aporta una protección anticorrosiva extrema y de largos intervalos al acero y la infraestructura, en capas más finas e inteligentes, en camino hacia lo 100% renovable.',
        it: 'Comprovato nelle atmosfere più severe da <em>30 anni</em> — e ancora in evoluzione. SteelKote porta una protezione anticorrosione estrema a lunghi intervalli su acciaio e infrastrutture, in strati più sottili e intelligenti, in cammino verso il 100% rinnovabile.',
        tr: '<em>30 yıldır</em> en zorlu atmosferlerde kanıtlanmış — ve hâlâ gelişmekte. SteelKote, çeliğe ve altyapıya uzun aralıklı aşırı korozyon korumasını daha ince, daha akıllı katlarla getiriyor, %100 yenilenebilir olma yolunda.', no: 'Bevist i <em>30 år</em> i de tøffeste atmosfærene — og fortsatt i utvikling. SteelKote bringer ekstrem korrosjonsbeskyttelse med lange intervaller til stål og infrastruktur, i tynnere, smartere lag, på vei mot 100% fornybar.', sv: 'Beprövad i <em>30 år</em> i de tuffaste atmosfärerna — och fortfarande under utveckling. SteelKote ger extremt, långintervalls korrosionsskydd till stål och infrastruktur, i tunnare, smartare lager, på väg mot 100% förnybar.' }],
      ['.bp-card b', {
        nl: ['Extreme corrosiebestendigheid','Tot 25-jarige intervallen','40% dunnere lagen','Water- &amp; onderdompelingsbestendig','NORSOK-gecertificeerd','Op weg naar 100% hernieuwbaar'],
        pl: ['Ekstremalna odporność na korozję','Interwały do 25 lat','Warstwy cieńsze o 40%','Odporne na wodę i zanurzenie','Certyfikat NORSOK','Ku 100% odnawialności'],
        ro: ['Rezistență extremă la coroziune','Intervale de până la 25 de ani','Straturi cu 40% mai subțiri','Rezistent la apă și imersiune','Certificat NORSOK','Către 100% regenerabil'],
        de: ['Extreme Korrosionsbeständigkeit','Intervalle bis zu 25 Jahre','40% dünnere Schichten','Wasser- &amp; tauchbeständig','NORSOK-zertifiziert','Auf dem Weg zu 100% erneuerbar'],
        fr: ['Résistance extrême à la corrosion','Intervalles jusqu\'à 25 ans','Couches 40% plus fines','Résistant à l\'eau &amp; à l\'immersion','Certifié NORSOK','En route vers le 100% renouvelable'],
        es: ['Resistencia extrema a la corrosión','Intervalos de hasta 25 años','Capas 40% más finas','Resistente al agua &amp; a la inmersión','Certificado NORSOK','En camino hacia lo 100% renovable'],
        it: ['Resistenza estrema alla corrosione','Intervalli fino a 25 anni','Strati 40% più sottili','Resistente all\'acqua &amp; all\'immersione','Certificato NORSOK','Verso il 100% rinnovabile'],
        tr: ['Aşırı korozyon direnci','25 yıla kadar aralıklar','%40 daha ince katlar','Su &amp; daldırma dayanımı','NORSOK sertifikalı','%100 yenilenebilir olma yolunda'], no: ['Ekstrem korrosjonsbestandighet','Inntil 25-årige intervaller','40% tynnere lag','Vann- &amp; neddykkingsbestandig','NORSOK-sertifisert','På vei mot 100% fornybar'], sv: ['Extrem korrosionsbeständighet','Upp till 25-åriga intervall','40% tunnare lager','Vatten- &amp; nedsänkningsbeständig','NORSOK-certifierad','På väg mot 100% förnybar'] }],
      ['.bp-card span', {
        nl: ['ISO 12944-prestaties in alle atmosferische corrosiviteitsklassen.','Lange beschermingsperiodes brengen groot-onderhoud — en kosten — tot een minimum.','Geavanceerde dunne-laag-technologie beschermt met veel minder coating per m².','Een dichte, waterdichte structuur, geschikt voor zoet, zout en brak onderdompelen.','Gecertificeerde systemen voor zwaar weer, marine en offshore.','Decennia conventionele kennis, nu opnieuw geformuleerd op een hernieuwbaar pad.'],
        pl: ['Wydajność ISO 12944 we wszystkich klasach korozyjności atmosferycznej.','Długie okresy ochrony minimalizują cykle dużych remontów i koszty.','Zaawansowana technologia cienkowarstwowa chroni przy znacznie mniejszej ilości powłoki na m².','Gęsta, wodoszczelna struktura odpowiednia do zanurzenia w wodzie słodkiej, słonej i słonawej.','Certyfikowane systemy do trudnych warunków pogodowych, morskich i offshore.','Dekady konwencjonalnej wiedzy, teraz przeformułowane na odnawialnej drodze.'],
        ro: ['Performanță ISO 12944 în toate clasele de corozivitate atmosferică.','Perioadele lungi de protecție reduc la minimum ciclurile de mentenanță majoră și costurile.','Tehnologia avansată în strat subțire protejează cu mult mai puțină acoperire pe m².','O structură densă, etanșă, potrivită pentru imersiune în apă dulce, sărată și salmastră.','Sisteme certificate pentru vreme grea, medii maritime și offshore.','Decenii de know-how convențional, acum reformulate pe un drum regenerabil.'],
        de: ['ISO 12944-Leistung in allen atmosphärischen Korrosivitätsklassen.','Lange Schutzperioden reduzieren Großinstandhaltung — und Kosten — auf ein Minimum.','Fortschrittliche Dünnschichttechnologie schützt mit deutlich weniger Beschichtung pro m².','Eine dichte, wasserdichte Struktur, geeignet für Süß-, Salz- und Brackwassereintauchen.','Zertifizierte Systeme für raues Wetter, maritime und Offshore-Einsätze.','Jahrzehnte konventionelles Wissen, jetzt neu formuliert auf einem erneuerbaren Weg.'],
        fr: ['Des performances ISO 12944 dans toutes les classes de corrosivité atmosphérique.','De longues périodes de protection réduisent au minimum la maintenance lourde — et les coûts.','Une technologie en couche mince avancée qui protège avec bien moins de revêtement par m².','Une structure dense et étanche, adaptée à l\'immersion en eau douce, salée et saumâtre.','Des systèmes certifiés pour les intempéries, le milieu marin et l\'offshore.','Des décennies de savoir-faire conventionnel, désormais reformulées sur une voie renouvelable.'],
        es: ['Rendimiento ISO 12944 en todas las clases de corrosividad atmosférica.','Los largos periodos de protección reducen al mínimo el mantenimiento mayor — y los costes.','La avanzada tecnología de capa fina protege con mucho menos recubrimiento por m².','Una estructura densa e impermeable, apta para inmersión en agua dulce, salada y salobre.','Sistemas certificados para climas severos, entornos marinos y offshore.','Décadas de conocimiento convencional, ahora reformuladas en una vía renovable.'],
        it: ['Prestazioni ISO 12944 in tutte le classi di corrosività atmosferica.','I lunghi periodi di protezione riducono al minimo la manutenzione straordinaria — e i costi.','L\'avanzata tecnologia a film sottile protegge con molto meno rivestimento per m².','Una struttura densa e impermeabile, adatta all\'immersione in acqua dolce, salata e salmastra.','Sistemi certificati per intemperie, ambienti marini e offshore.','Decenni di know-how convenzionale, ora riformulate su un percorso rinnovabile.'],
        tr: ['Tüm atmosferik korozyon sınıflarında ISO 12944 performansı.','Uzun koruma süreleri, büyük bakımı — ve maliyetleri — en aza indirir.','Gelişmiş ince film teknolojisi, m² başına çok daha az kaplamayla korur.','Tatlı, tuzlu ve acı suya daldırma için uygun, yoğun ve su geçirmez bir yapı.','Ağır hava koşulları, deniz ve açık deniz için sertifikalı sistemler.','Onlarca yıllık geleneksel uzmanlık, şimdi yenilenebilir bir yolda yeniden formüle edildi.'], no: ['ISO 12944-ytelse i alle atmosfæriske korrosivitetsklasser.','Lange beskyttelsesperioder holder hovedvedlikehold — og kostnader — på et minimum.','Avansert tynnsjikt-teknologi beskytter med langt mindre belegg per m².','En tett, vanntett struktur, egnet for neddykking i ferskvann, saltvann og brakkvann.','Sertifiserte systemer for hardt vær, marine og offshore.','Tiår med konvensjonell kunnskap, nå reformulert på et fornybart spor.'], sv: ['ISO 12944-prestanda i alla atmosfäriska korrosivitetsklasser.','Långa skyddsperioder håller större underhåll — och kostnader — på ett minimum.','Avancerad tunnskiktsteknik skyddar med långt mindre beläggning per m².','En tät, vattentät struktur, lämplig för nedsänkning i sötvatten, saltvatten och bräckt vatten.','Certifierade system för hårt väder, marin och offshore.','Decennier av konventionellt kunnande, nu omformulerat på ett förnybart spår.'] }],
      ['h2', {
        nl: ['Bescherming die het <span class="bp-accent">langer volhoudt</span> dan het weer','Kies SteelKote'],
        pl: ['Ochrona, która <span class="bp-accent">przetrwa</span> pogodę','Wybierz SteelKote'],
        ro: ['Protecție care <span class="bp-accent">depășește</span> vremea','Specifică SteelKote'],
        de: ['Schutz, der <span class="bp-accent">länger durchhält</span> als das Wetter','SteelKote wählen'],
        fr: ['Une protection qui <span class="bp-accent">survit</span> aux intempéries','Choisir SteelKote'],
        es: ['Protección que <span class="bp-accent">resiste más</span> que el clima','Elija SteelKote'],
        it: ['Protezione che <span class="bp-accent">dura più a lungo</span> del tempo','Scegli SteelKote'],
        tr: ['Hava koşullarından <span class="bp-accent">daha uzun dayanan</span> koruma','SteelKote\'u seçin'], no: ['Beskyttelse som <span class="bp-accent">varer lenger</span> enn været','Velg SteelKote'], sv: ['Skydd som <span class="bp-accent">håller längre</span> än vädret','Välj SteelKote'] }],
      ['.bp-list span', {
        nl: ['Epoxyprimers en urethaan toplagen, bewezen in de meest extreme atmosferen.','Blijvende flexibiliteit en een ondoordringbare, slijtvaste structuur.','Lagere kosten per m³ door hogere vaste stof en dunnere lagen.'],
        pl: ['Podkłady epoksydowe i nawierzchnie uretanowe sprawdzone w najbardziej ekstremalnych atmosferach.','Trwała elastyczność i nieprzenikliwa, odporna na ścieranie struktura.','Niższy koszt na m³ dzięki wyższej zawartości części stałych i cieńszym powłokom.'],
        ro: ['Grunduri epoxidice și straturi uretanice dovedite în cele mai extreme atmosfere.','Flexibilitate durabilă și o structură impenetrabilă, rezistentă la uzură.','Cost mai mic pe m³ prin conținut mai mare de substanțe solide și pelicule mai subțiri.'],
        de: ['Epoxidgrundierungen und Urethan-Decklacke, bewährt in den extremsten Atmosphären.','Dauerhafte Flexibilität und eine undurchdringliche, verschleißfeste Struktur.','Geringere Kosten pro m³ durch höheren Festkörperanteil und dünnere Schichten.'],
        fr: ['Des primaires époxy et des couches de finition uréthane, éprouvés dans les atmosphères les plus extrêmes.','Une flexibilité durable et une structure impénétrable, résistante à l\'usure.','Un coût par m³ réduit grâce à un extrait sec plus élevé et des couches plus fines.'],
        es: ['Imprimaciones epoxi y capas de acabado de uretano, probadas en las atmósferas más extremas.','Flexibilidad duradera y una estructura impenetrable y resistente al desgaste.','Menor coste por m³ gracias a un mayor contenido de sólidos y capas más finas.'],
        it: ['Primer epossidici e strati di finitura uretanici, comprovati nelle atmosfere più estreme.','Flessibilità duratura e una struttura impenetrabile, resistente all\'usura.','Costo inferiore al m³ grazie a un maggiore contenuto di solidi e a strati più sottili.'],
        tr: ['En zorlu atmosferlerde kanıtlanmış epoksi astarlar ve üretan son katlar.','Kalıcı esneklik ve geçirimsiz, aşınmaya dayanıklı bir yapı.','Daha yüksek katı madde oranı ve daha ince katlar sayesinde m³ başına daha düşük maliyet.'], no: ['Epoksy-primere og uretantopplag, bevist i de mest ekstreme atmosfærene.','Varig fleksibilitet og en ugjennomtrengelig, slitebestandig struktur.','Lavere kostnad per m² gjennom høyere tørrstoff og tynnere lag.'], sv: ['Epoxiprimers och uretantopplager, beprövade i de mest extrema atmosfärerna.','Bestående flexibilitet och en ogenomtränglig, nötningsbeständig struktur.','Lägre kostnad per m² genom högre torrhalt och tunnare lager.'] }],
      ['.bp-stat .l', {
        nl: ['Bewezen beschermingservaring','Onderhoudsintervallen','Dunnere lagen','Alle corrosiviteitsklassen'],
        pl: ['Sprawdzonego doświadczenia w ochronie','Interwały konserwacji','Cieńsze warstwy','Wszystkie klasy korozyjności'],
        ro: ['De experiență dovedită în protecție','Intervale de mentenanță','Straturi mai subțiri','Toate clasele de corozivitate'],
        de: ['Bewährte Schutzerfahrung','Wartungsintervalle','Dünnere Schichten','Alle Korrosivitätsklassen'],
        fr: ['D\'expérience éprouvée en protection','Intervalles de maintenance','Couches plus fines','Toutes les classes de corrosivité'],
        es: ['De experiencia probada en protección','Intervalos de mantenimiento','Capas más finas','Todas las clases de corrosividad'],
        it: ['Di esperienza comprovata nella protezione','Intervalli di manutenzione','Strati più sottili','Tutte le classi di corrosività'],
        tr: ['Kanıtlanmış koruma deneyimi','Bakım aralıkları','Daha ince katlar','Tüm korozyon sınıfları'], no: ['Bevist beskyttelseserfaring','Vedlikeholdsintervaller','Tynnere lag','Alle korrosivitetsklasser'], sv: ['Beprövad skyddserfarenhet','Underhållsintervall','Tunnare lager','Alla korrosivitetsklasser'] }],
      ['.bp-band p', {
        nl: 'Ontdek het SteelKote-assortiment in de Baril Coatings-catalogus — met datasheets en veiligheidsbladen — of bespreek je project met onze coatingexperts.',
        pl: 'Poznaj gamę SteelKote w katalogu Baril Coatings — z kartami technicznymi i charakterystykami — lub omów swój projekt z naszymi ekspertami.',
        ro: 'Explorează gama SteelKote în catalogul Baril Coatings — cu fișe tehnice și de securitate — sau discută proiectul tău cu experții noștri.',
        de: 'Entdecken Sie das SteelKote-Sortiment im Baril Coatings-Katalog — mit Datenblättern und Sicherheitsdatenblättern — oder besprechen Sie Ihr Projekt mit unseren Beschichtungsexperten.',
        fr: 'Découvrez la gamme SteelKote dans le catalogue Baril Coatings — avec fiches techniques et de sécurité — ou discutez de votre projet avec nos experts en revêtements.',
        es: 'Descubra la gama SteelKote en el catálogo de Baril Coatings — con fichas técnicas y de seguridad — o comente su proyecto con nuestros expertos en recubrimientos.',
        it: 'Scopri la gamma SteelKote nel catalogo Baril Coatings — con schede tecniche e di sicurezza — o discuti il tuo progetto con i nostri esperti di rivestimenti.',
        tr: 'SteelKote serisini Baril Coatings kataloğunda keşfedin — teknik ve güvenlik veri sayfalarıyla — ya da projenizi kaplama uzmanlarımızla görüşün.', no: 'Oppdag SteelKote-sortimentet i Baril Coatings-katalogen — med datablad og sikkerhetsdatablad — eller diskuter prosjektet ditt med coatingekspertene våre.', sv: 'Upptäck SteelKote-sortimentet i Baril Coatings-katalogen — med datablad och säkerhetsdatablad — eller diskutera ditt projekt med våra beläggningsexperter.' }],
      ['.foot-claim', {
        nl: '<span class="bp-accent">SteelKote</span> — heavy-duty beschermende coatings.',
        pl: '<span class="bp-accent">SteelKote</span> — wytrzymałe powłoki ochronne.',
        ro: '<span class="bp-accent">SteelKote</span> — acoperiri de protecție de mare rezistență.',
        de: '<span class="bp-accent">SteelKote</span> — Hochleistungs-Schutzbeschichtungen.',
        fr: '<span class="bp-accent">SteelKote</span> — revêtements de protection haute résistance.',
        es: '<span class="bp-accent">SteelKote</span> — recubrimientos protectores de alta resistencia.',
        it: '<span class="bp-accent">SteelKote</span> — rivestimenti protettivi heavy-duty.',
        tr: '<span class="bp-accent">SteelKote</span> — ağır hizmet koruyucu kaplamalar.', no: '<span class="bp-accent">SteelKote</span> — heavy-duty beskyttende belegg.', sv: '<span class="bp-accent">SteelKote</span> — heavy-duty skyddande beläggningar.' }]
    ],

    bariline: [
      ['.bp-tag', { nl: 'Biobased alkyd beschermende coatings', pl: 'Biobazowe alkidowe powłoki ochronne', ro: 'Acoperiri de protecție alchidice biobazate', de: 'Biobasierte Alkyd-Schutzbeschichtungen', fr: 'Revêtements de protection alkydes biosourcés', es: 'Recubrimientos protectores alquídicos de base biológica', it: 'Rivestimenti protettivi alchidici biobased', tr: 'Biyobazlı alkid koruyucu kaplamalar', no: 'Biobaserte alkyd-beskyttende belegg', sv: 'Biobaserade alkyd-skyddande beläggningar' }],
      ['.bp-sub', {
        nl: 'Eencomponent biobased alkydcoatings — anticorrosieve bescherming in kleur voor staalconstructie. <strong>Eenvoudig aan te brengen, snel te verwerken, simpel te specificeren.</strong>',
        pl: 'Jednoskładnikowe biobazowe powłoki alkidowe — antykorozyjna ochrona w kolorze dla konstrukcji stalowych. <strong>Łatwe w aplikacji, szybkie w obróbce, proste w doborze.</strong>',
        ro: 'Acoperiri alchidice biobazate monocomponent — protecție anticorozivă în culoare pentru construcții din oțel. <strong>Ușor de aplicat, rapid de manipulat, simplu de specificat.</strong>',
        de: 'Einkomponentige biobasierte Alkydbeschichtungen — Korrosionsschutz in Farbe für den Stahlbau. <strong>Einfach aufzutragen, schnell zu verarbeiten, simpel zu spezifizieren.</strong>',
        fr: 'Revêtements alkydes biosourcés monocomposants — protection anticorrosion en couleur pour la construction acier. <strong>Faciles à appliquer, rapides à mettre en œuvre, simples à spécifier.</strong>',
        es: 'Recubrimientos alquídicos de base biológica monocomponente — protección anticorrosiva en color para la construcción en acero. <strong>Fáciles de aplicar, rápidos de procesar, sencillos de especificar.</strong>',
        it: 'Rivestimenti alchidici biobased monocomponente — protezione anticorrosione in colore per la carpenteria in acciaio. <strong>Facili da applicare, rapidi da lavorare, semplici da specificare.</strong>',
        tr: 'Tek bileşenli biyobazlı alkid kaplamalar — çelik konstrüksiyon için renkli antikorozif koruma. <strong>Uygulaması kolay, işlenmesi hızlı, belirlenmesi basit.</strong>', no: 'Énkomponents biobaserte alkydbelegg — antikorrosiv beskyttelse i farge for stålkonstruksjon. <strong>Enkle å påføre, raske å håndtere, enkle å spesifisere.</strong>', sv: 'Enkomponents biobaserade alkydbeläggningar — antikorrosivt skydd i färg för stålkonstruktion. <strong>Lätta att applicera, snabba att hantera, enkla att specificera.</strong>' }],
      ['.bp-quick span', {
        nl: ['<b>1K</b> eencomponent','<b>Biobased</b> alkyd','<b>Direct-op-metaal</b>','<b>Snelle</b> verwerking'],
        pl: ['<b>1K</b> jednoskładnikowy','Alkid <b>biobazowy</b>','<b>Bezpośrednio na metal</b>','<b>Szybka</b> obróbka'],
        ro: ['<b>1K</b> monocomponent','Alchidic <b>biobazat</b>','<b>Direct pe metal</b>','Manipulare <b>rapidă</b>'],
        de: ['<b>1K</b> einkomponentig','<b>Biobasiertes</b> Alkyd','<b>Direkt-auf-Metall</b>','<b>Schnelle</b> Verarbeitung'],
        fr: ['<b>1K</b> monocomposant','Alkyde <b>biosourcé</b>','<b>Direct-sur-métal</b>','Mise en œuvre <b>rapide</b>'],
        es: ['<b>1K</b> monocomponente','Alquídico <b>de base biológica</b>','<b>Directo-sobre-metal</b>','Procesado <b>rápido</b>'],
        it: ['<b>1K</b> monocomponente','Alchidico <b>biobased</b>','<b>Diretto-su-metallo</b>','Lavorazione <b>rapida</b>'],
        tr: ['<b>1K</b> tek bileşen','<b>Biyobazlı</b> alkid','<b>Doğrudan-metale</b>','<b>Hızlı</b> işleme'], no: ['<b>1K</b> énkomponent','<b>Biobasert</b> alkyd','<b>Direkte-på-metall</b>','<b>Rask</b> håndtering'], sv: ['<b>1K</b> enkomponent','<b>Biobaserad</b> alkyd','<b>Direkt-på-metall</b>','<b>Snabb</b> hantering'] }],
      ['.eyebrow', { nl: ['Waarom Bariline','In de praktijk'], pl: ['Dlaczego Bariline','W praktyce'], ro: ['De ce Bariline','În practică'], de: ['Warum Bariline','In der Praxis'], fr: ['Pourquoi Bariline','En pratique'], es: ['Por qué Bariline','En la práctica'], it: ['Perché Bariline','Nella pratica'], tr: ['Neden Bariline','Pratikte'], no: ['Hvorfor Bariline','I praksis'], sv: ['Varför Bariline','I praktiken'] }],
      ['.bp-quote', {
        nl: 'Niet elke klus heeft een tweecomponentensysteem nodig. Bariline houdt staalbescherming <em>simpel</em> — een eencomponent biobased alkyd die direct op metaal gaat, snel droogt en in kleur afwerkt.',
        pl: 'Nie każde zadanie wymaga systemu dwuskładnikowego. Bariline utrzymuje ochronę stali <em>prostą</em> — jednoskładnikowy biobazowy alkid, który nakłada się bezpośrednio na metal, szybko schnie i wykańcza w kolorze.',
        ro: 'Nu orice lucrare are nevoie de un sistem bicomponent. Bariline păstrează protecția oțelului <em>simplă</em> — un alchid biobazat monocomponent care se aplică direct pe metal, se usucă rapid și finisează în culoare.',
        de: 'Nicht jede Aufgabe braucht ein Zweikomponentensystem. Bariline hält den Stahlschutz <em>einfach</em> — ein einkomponentiges biobasiertes Alkyd, das direkt auf Metall geht, schnell trocknet und in Farbe abschließt.',
        fr: 'Tous les chantiers n\'ont pas besoin d\'un système bicomposant. Bariline garde la protection de l\'acier <em>simple</em> — un alkyde biosourcé monocomposant qui s\'applique directement sur le métal, sèche vite et se termine en couleur.',
        es: 'No todos los trabajos necesitan un sistema bicomponente. Bariline mantiene la protección del acero <em>sencilla</em> — un alquídico de base biológica monocomponente que se aplica directamente sobre el metal, seca rápido y acaba en color.',
        it: 'Non ogni lavoro richiede un sistema bicomponente. Bariline mantiene la protezione dell\'acciaio <em>semplice</em> — un alchidico biobased monocomponente che si applica direttamente sul metallo, asciuga in fretta e rifinisce in colore.',
        tr: 'Her iş çift bileşenli bir sistem gerektirmez. Bariline çelik korumasını <em>basit</em> tutar — doğrudan metale uygulanan, hızlı kuruyan ve renkli son kat veren tek bileşenli biyobazlı bir alkid.', no: 'Ikke enhver jobb trenger et tokomponentsystem. Bariline holder stålbeskyttelse <em>enkel</em> — en énkomponents biobasert alkyd som går direkte på metall, tørker raskt og avsluttes i farge.', sv: 'Inte varje jobb behöver ett tvåkomponentssystem. Bariline håller stålskydd <em>enkelt</em> — en enkomponents biobaserad alkyd som går direkt på metall, torkar snabbt och avslutas i färg.' }],
      ['.bp-card b', {
        nl: ['Eencomponent eenvoud','Biobased alkyd','Direct-op-metaal','Enkellaags optie','Snel drogen &amp; verwerken','Kleurafwerkingen'],
        pl: ['Jednoskładnikowa prostota','Biobazowy alkid','Bezpośrednio na metal','Opcja jednowarstwowa','Szybkie schnięcie i obróbka','Wykończenia kolorowe'],
        ro: ['Simplitate monocomponent','Alchid biobazat','Direct pe metal','Opțiune monostrat','Uscare și manipulare rapide','Finisaje în culoare'],
        de: ['Einkomponentige Einfachheit','Biobasiertes Alkyd','Direkt-auf-Metall','Einschicht-Option','Schnelles Trocknen &amp; Verarbeiten','Farbabschlüsse'],
        fr: ['Simplicité monocomposant','Alkyde biosourcé','Direct-sur-métal','Option monocouche','Séchage &amp; mise en œuvre rapides','Finitions en couleur'],
        es: ['Simplicidad monocomponente','Alquídico de base biológica','Directo-sobre-metal','Opción monocapa','Secado &amp; procesado rápidos','Acabados en color'],
        it: ['Semplicità monocomponente','Alchidico biobased','Diretto-su-metallo','Opzione monostrato','Asciugatura &amp; lavorazione rapide','Finiture in colore'],
        tr: ['Tek bileşenli sadelik','Biyobazlı alkid','Doğrudan-metale','Tek kat seçeneği','Hızlı kuruma &amp; işleme','Renkli son katlar'], no: ['Énkomponents enkelhet','Biobasert alkyd','Direkte-på-metall','Enkeltlags-alternativ','Rask tørk &amp; håndtering','Fargefinisher'], sv: ['Enkomponents enkelhet','Biobaserad alkyd','Direkt-på-metall','Enskikts-alternativ','Snabb torkning &amp; hantering','Färgfinisher'] }],
      ['.bp-card span', {
        nl: ['Geen mengen, geen potlife — een enkelpak-systeem dat eenvoudig aan te brengen en te bewaren is.','Alkydchemie op meer hernieuwbare grondstoffen — fossiel gehalte teruggebracht.','Gaat direct op gestraald staal — primer en afwerking in één in veel toepassingen.','Eén laag anticorrosieve bescherming, in kleur, voor staalconstructies en containers.','Snel droog en klaar voor verwerking — houdt bouwplanningen op schema.','Anticorrosieve prestaties met een afgewerkte kleur — van shopprimer tot toplaag.'],
        pl: ['Bez mieszania, bez czasu przydatności — system jednopojemnikowy, łatwy w aplikacji i przechowywaniu.','Chemia alkidowa oparta na bardziej odnawialnych surowcach — ograniczona zawartość kopalna.','Nakłada się bezpośrednio na śrutowaną stal — podkład i wykończenie w jednym w wielu zastosowaniach.','Jedna warstwa ochrony antykorozyjnej, w kolorze, dla konstrukcji stalowych i kontenerów.','Szybko schnie i jest gotowy do obróbki — utrzymuje harmonogramy budowy.','Wydajność antykorozyjna z gotowym kolorem — od podkładu warsztatowego po nawierzchnię.'],
        ro: ['Fără amestecare, fără timp de utilizare — un sistem monopachet, ușor de aplicat și depozitat.','Chimie alchidică bazată pe materii prime mai regenerabile — conținut fosil redus.','Se aplică direct pe oțelul sablat — grund și finisaj într-unul în multe aplicații.','Un strat de protecție anticorozivă, în culoare, pentru construcții din oțel și containere.','Se usucă repede și este gata de manipulat — menținând graficele de construcție.','Performanță anticorozivă cu o culoare finisată — de la grund de atelier la stratul final.'],
        de: ['Kein Mischen, keine Topfzeit — ein Einpack-System, das einfach aufzutragen und zu lagern ist.','Alkydchemie auf Basis erneuerbarerer Rohstoffe — der fossile Anteil ist reduziert.','Geht direkt auf gestrahlten Stahl — Grundierung und Decklack in einem bei vielen Anwendungen.','Eine Schicht Korrosionsschutz, in Farbe, für Stahlkonstruktionen und Container.','Schnell trocken und verarbeitungsbereit — hält Bauzeitpläne im Plan.','Korrosionsschutzleistung mit fertiger Farbe — vom Shopprimer bis zum Decklack.'],
        fr: ['Pas de mélange, pas de durée de vie en pot — un système monoboîte, facile à appliquer et à stocker.','Une chimie alkyde sur matières premières plus renouvelables — la teneur fossile est réduite.','S\'applique directement sur l\'acier grenaillé — primaire et finition en un seul dans de nombreuses applications.','Une couche de protection anticorrosion, en couleur, pour structures acier et conteneurs.','Sèche vite et prêt à être manipulé — pour tenir les plannings de chantier.','Des performances anticorrosion avec une couleur finie — du shop-primer à la couche de finition.'],
        es: ['Sin mezcla, sin vida útil de mezcla — un sistema de un solo envase, fácil de aplicar y almacenar.','Química alquídica sobre materias primas más renovables — contenido fósil reducido.','Se aplica directamente sobre acero granallado — imprimación y acabado en uno en muchas aplicaciones.','Una capa de protección anticorrosiva, en color, para estructuras de acero y contenedores.','Seca rápido y listo para manipular — mantiene los plazos de obra al día.','Rendimiento anticorrosivo con un color acabado — desde el shop-primer hasta la capa de acabado.'],
        it: ['Niente miscelazione, niente pot life — un sistema monoconfezione, facile da applicare e conservare.','Chimica alchidica basata su materie prime più rinnovabili — contenuto fossile ridotto.','Si applica direttamente sull\'acciaio sabbiato — primer e finitura in uno in molte applicazioni.','Uno strato di protezione anticorrosione, in colore, per strutture in acciaio e container.','Asciuga in fretta ed è pronto alla lavorazione — mantenendo i tempi di cantiere.','Prestazioni anticorrosione con un colore finito — dallo shop-primer allo strato finale.'],
        tr: ['Karıştırma yok, kullanım ömrü yok — uygulaması ve saklaması kolay, tek ambalajlı bir sistem.','Daha yenilenebilir hammaddelere dayalı alkid kimyası — fosil içeriği azaltılmış.','Doğrudan kumlanmış çeliğe uygulanır — birçok uygulamada astar ve son kat bir arada.','Çelik yapılar ve konteynerler için renkli, tek kat antikorozif koruma.','Hızlı kurur ve işlemeye hazır — inşaat programlarını zamanında tutar.','Bitmiş bir renkle antikorozif performans — shop-primerden son kata kadar.'], no: ['Ingen blanding, ingen potlife — et enpakkssystem som er enkelt å påføre og lagre.','Alkydkjemi på mer fornybare råvarer — fossilt innhold redusert.','Går direkte på blåst stål — primer og finish i ett i mange bruksområder.','Ett strøk antikorrosiv beskyttelse, i farge, for stålkonstruksjoner og containere.','Rask tørk og klar til håndtering — holder byggeplaner på skinner.','Antikorrosiv ytelse med en ferdig farge — fra shopprimer til topplag.'], sv: ['Ingen blandning, ingen pottid — ett enpaketssystem som är lätt att applicera och förvara.','Alkydkemi på mer förnybara råvaror — fossilt innehåll reducerat.','Går direkt på blästrat stål — primer och finish i ett i många tillämpningar.','Ett lager antikorrosivt skydd, i färg, för stålkonstruktioner och containrar.','Snabb torkning och redo att hantera — håller byggscheman på rätt spår.','Antikorrosiv prestanda med en färdig färg — från shopprimer till topplager.'] }],
      ['h2', {
        nl: ['Eenvoudig aan te brengen,<br><span class="bp-accent">snel</span> klaar','Kies Bariline'],
        pl: ['Łatwy w aplikacji,<br><span class="bp-accent">szybki</span> w wykończeniu','Wybierz Bariline'],
        ro: ['Ușor de aplicat,<br><span class="bp-accent">rapid</span> de finisat','Specifică Bariline'],
        de: ['Einfach aufzutragen,<br><span class="bp-accent">schnell</span> fertig','Bariline wählen'],
        fr: ['Facile à appliquer,<br><span class="bp-accent">vite</span> terminé','Choisir Bariline'],
        es: ['Fácil de aplicar,<br><span class="bp-accent">rápido</span> de terminar','Elija Bariline'],
        it: ['Facile da applicare,<br><span class="bp-accent">veloce</span> da finire','Scegli Bariline'],
        tr: ['Uygulaması kolay,<br><span class="bp-accent">hızlı</span> biten','Bariline\'ı seçin'], no: ['Enkel å påføre,<br><span class="bp-accent">rask</span> å fullføre','Velg Bariline'], sv: ['Lätt att applicera,<br><span class="bp-accent">snabb</span> att slutföra','Välj Bariline'] }],
      ['.bp-list span', {
        nl: ['Ideaal voor staalconstructies en containers in landelijke tot licht-industriële omgevingen.','Van kortdurende shopprimer tot langdurige bescherming, met het Bariline-primersysteem.','Een praktische, kostenefficiënte keuze waar snelheid en eenvoud het belangrijkst zijn.'],
        pl: ['Idealny do konstrukcji stalowych i kontenerów w środowiskach wiejskich i lekko przemysłowych.','Od krótkotrwałego podkładu warsztatowego po długoterminową ochronę, z systemem podkładu Bariline.','Praktyczny, opłacalny wybór tam, gdzie liczą się szybkość i prostota.'],
        ro: ['Ideal pentru construcții din oțel și containere în medii rurale până la ușor industriale.','De la grund de atelier pe termen scurt la protecție pe termen lung, cu sistemul de grund Bariline.','O alegere practică și economică acolo unde contează viteza și simplitatea.'],
        de: ['Ideal für Stahlkonstruktionen und Container in ländlichen bis leicht industriellen Umgebungen.','Vom kurzzeitigen Shopprimer bis zum langfristigen Schutz, mit dem Bariline-Grundierungssystem.','Eine praktische, kosteneffiziente Wahl, wo Geschwindigkeit und Einfachheit am wichtigsten sind.'],
        fr: ['Idéal pour les structures acier et les conteneurs en environnements ruraux à légèrement industriels.','Du shop-primer de courte durée à la protection longue durée, avec le système de primaire Bariline.','Un choix pratique et économique là où la rapidité et la simplicité comptent le plus.'],
        es: ['Ideal para estructuras de acero y contenedores en entornos rurales a ligeramente industriales.','Desde el shop-primer de corta duración hasta la protección de larga duración, con el sistema de imprimación Bariline.','Una elección práctica y rentable allí donde la rapidez y la sencillez son lo más importante.'],
        it: ['Ideale per strutture in acciaio e container in ambienti da rurali a leggermente industriali.','Dallo shop-primer di breve durata alla protezione di lunga durata, con il sistema di primer Bariline.','Una scelta pratica ed economica dove velocità e semplicità contano di più.'],
        tr: ['Kırsaldan hafif endüstriyele kadar ortamlardaki çelik yapılar ve konteynerler için ideal.','Kısa süreli shop-primerden uzun süreli korumaya kadar, Bariline astar sistemiyle.','Hız ve sadeliğin en önemli olduğu yerlerde pratik, uygun maliyetli bir tercih.'], no: ['Ideell for stålkonstruksjoner og containere i landlige til lett-industrielle miljøer.','Fra kortvarig shopprimer til langvarig beskyttelse, med Bariline-primersystemet.','Et praktisk, kostnadseffektivt valg der hastighet og enkelhet betyr mest.'], sv: ['Idealisk för stålkonstruktioner och containrar i lantliga till lättindustriella miljöer.','Från kortvarig shopprimer till långvarigt skydd, med Bariline-primersystemet.','Ett praktiskt, kostnadseffektivt val där snabbhet och enkelhet betyder mest.'] }],
      ['.bp-stat .l', {
        nl: ['Eencomponent, geen mengen','Biobased alkydchemie','Direct-op-metaal toepassing','Snel drogen &amp; verwerken'],
        pl: ['Jednoskładnikowy, bez mieszania','Biobazowa chemia alkidowa','Aplikacja bezpośrednio na metal','Szybkie schnięcie i obróbka'],
        ro: ['Monocomponent, fără amestecare','Chimie alchidică biobazată','Aplicare direct pe metal','Uscare și manipulare rapide'],
        de: ['Einkomponentig, kein Mischen','Biobasierte Alkydchemie','Direkt-auf-Metall-Anwendung','Schnelles Trocknen &amp; Verarbeiten'],
        fr: ['Monocomposant, sans mélange','Chimie alkyde biosourcée','Application direct-sur-métal','Séchage &amp; mise en œuvre rapides'],
        es: ['Monocomponente, sin mezcla','Química alquídica de base biológica','Aplicación directo-sobre-metal','Secado &amp; procesado rápidos'],
        it: ['Monocomponente, senza miscelazione','Chimica alchidica biobased','Applicazione diretto-su-metallo','Asciugatura &amp; lavorazione rapide'],
        tr: ['Tek bileşen, karıştırma yok','Biyobazlı alkid kimyası','Doğrudan-metale uygulama','Hızlı kuruma &amp; işleme'], no: ['Énkomponent, ingen blanding','Biobasert alkydkjemi','Direkte-på-metall-påføring','Rask tørk &amp; håndtering'], sv: ['Enkomponent, ingen blandning','Biobaserad alkydkemi','Direkt-på-metall-applicering','Snabb torkning &amp; hantering'] }],
      ['.bp-band p', {
        nl: 'Ontdek het Bariline-assortiment in de Baril Coatings-catalogus — met datasheets en veiligheidsbladen — of praat met onze coatingexperts.',
        pl: 'Poznaj gamę Bariline w katalogu Baril Coatings — z kartami technicznymi i charakterystykami — lub porozmawiaj z naszymi ekspertami.',
        ro: 'Explorează gama Bariline în catalogul Baril Coatings — cu fișe tehnice și de securitate — sau discută cu experții noștri.',
        de: 'Entdecken Sie das Bariline-Sortiment im Baril Coatings-Katalog — mit Datenblättern und Sicherheitsdatenblättern — oder sprechen Sie mit unseren Beschichtungsexperten.',
        fr: 'Découvrez la gamme Bariline dans le catalogue Baril Coatings — avec fiches techniques et de sécurité — ou parlez à nos experts en revêtements.',
        es: 'Descubra la gama Bariline en el catálogo de Baril Coatings — con fichas técnicas y de seguridad — o hable con nuestros expertos en recubrimientos.',
        it: 'Scopri la gamma Bariline nel catalogo Baril Coatings — con schede tecniche e di sicurezza — o parla con i nostri esperti di rivestimenti.',
        tr: 'Bariline serisini Baril Coatings kataloğunda keşfedin — teknik ve güvenlik veri sayfalarıyla — ya da kaplama uzmanlarımızla konuşun.', no: 'Oppdag Bariline-sortimentet i Baril Coatings-katalogen — med datablad og sikkerhetsdatablad — eller snakk med coatingekspertene våre.', sv: 'Upptäck Bariline-sortimentet i Baril Coatings-katalogen — med datablad och säkerhetsdatablad — eller prata med våra beläggningsexperter.' }],
      ['.foot-claim', {
        nl: '<span class="bp-accent">Bariline</span> — biobased alkyd beschermende coatings.',
        pl: '<span class="bp-accent">Bariline</span> — biobazowe alkidowe powłoki ochronne.',
        ro: '<span class="bp-accent">Bariline</span> — acoperiri de protecție alchidice biobazate.',
        de: '<span class="bp-accent">Bariline</span> — biobasierte Alkyd-Schutzbeschichtungen.',
        fr: '<span class="bp-accent">Bariline</span> — revêtements de protection alkydes biosourcés.',
        es: '<span class="bp-accent">Bariline</span> — recubrimientos protectores alquídicos de base biológica.',
        it: '<span class="bp-accent">Bariline</span> — rivestimenti protettivi alchidici biobased.',
        tr: '<span class="bp-accent">Bariline</span> — biyobazlı alkid koruyucu kaplamalar.', no: '<span class="bp-accent">Bariline</span> — biobaserte alkyd-beskyttende belegg.', sv: '<span class="bp-accent">Bariline</span> — biobaserade alkyd-skyddande beläggningar.' }]
    ]
  };

  const brand = (document.body.dataset.brand || '').toLowerCase();
  const MAP = COMMON.concat(MAPS[brand] || []);

  const flagBox = document.getElementById('langflags');
  let lang = 'en';
  try { lang = localStorage.getItem('baril-coatings-lang') || 'en'; } catch (e) {}
  if (!['en', 'nl', 'pl', 'ro', 'de', 'fr', 'es', 'it', 'tr', 'no', 'sv'].includes(lang)) lang = 'en';

  function apply(l) {
    for (const [sel, dict] of MAP) {
      document.querySelectorAll(sel).forEach((el, i) => {
        if (el.dataset.en == null) el.dataset.en = el.innerHTML;
        let v;
        if (l === 'en') { v = (dict && dict.en != null) ? dict.en : el.dataset.en; }
        else { const d = dict ? dict[l] : null; v = Array.isArray(d) ? d[i] : (i === 0 ? d : null); }
        if (v == null) return;
        if (el.innerHTML !== v) el.innerHTML = v;
      });
    }
    document.documentElement.lang = l;
    if (flagBox) { flagBox.querySelectorAll('button[data-lang]').forEach(b => b.classList.toggle('active', b.dataset.lang === l)); const _c = flagBox.querySelector('.flag-current'), _s = flagBox.querySelector('button[data-lang="' + l + '"] .flag'); if (_c && _s) _c.src = _s.getAttribute('src'); }
    try { localStorage.setItem('baril-coatings-lang', l); } catch (e) {}
  }

  if (flagBox) flagBox.querySelectorAll('button[data-lang]').forEach(b => b.addEventListener('click', () => {
    lang = b.dataset.lang; if (!['en', 'nl', 'pl', 'ro', 'de', 'fr', 'es', 'it', 'tr', 'no', 'sv'].includes(lang)) lang = 'en';
    apply(lang);
  }));

  apply(lang);
})();
